"""
Dynamic content library for Seasonal Horizon.
Multilingual support: English (en) and German (de).
"""

# ===== FORECAST NARRATIVES =====
FORECAST_NARRATIVES = {
    "rain_clearing_soon": {
        "en": [
            "Grey skies today, but the forecast shows {clear_day} breaking through—just {days_until} more days to wait.",
            "The rain is temporary. By {clear_day}, the clouds lift and you'll have your moment in the sun.",
            "Hold steady through the grey. {clear_day} brings the clearing you're waiting for.",
            "This wet stretch has an end date: {clear_day}. Mark your calendar.",
            "Today's drizzle is just weather passing through. {clear_day}'s sunshine is coming.",
            "The clouds are visitors, not residents. They leave by {clear_day}.",
            "Patience pays: {days_until} days of grey, then {clear_day} delivers clear skies.",
            "Rain now, but I can see {clear_day} on the forecast—good conditions are coming.",
            "Every rainy streak has its last day. This one ends before {clear_day}.",
            "Wet windows today, but {clear_day} is circled on the weather chart.",
        ],
        "de": [
            "Heute noch grau, aber die Aussichten bessern sich: Am {clear_day} kommt die Sonne durch – nur noch {days_until} Tage.",
            "Regen ist kein Dauerzustand. Bis {clear_day} verziehen sich die Wolken und machen Platz für Sonne.",
            "Halt durch bei dem Grau. Der {clear_day} bringt die Aufhellung, auf die du wartest.",
            "Diese Regenphase hat ein Ablaufdatum: {clear_day}. Den Tag kannst du dir schon mal markieren.",
            "Wolken sind nur Besucher, keine Dauergäste. Spätestens am {clear_day} sind sie weg.",
            "Geduld lohnt sich: noch {days_until} Tage Grau, dann liefert der {clear_day} blauen Himmel.",
            "Aktuell noch nass, aber der {clear_day} sieht auf der Karte schon richtig gut aus.",
            "Lass den Kopf nicht hängen – das Wetter dreht sich. Am {clear_day} ist Besserung in Sicht.",
            "Nur noch ein kurzes Durchhalten: In {days_until} Tagen, am {clear_day}, übernimmt wieder die Sonne.",
            "Der Blick auf die Vorhersage tröstet: Am {clear_day} ist Schluss mit dem Grau.",
            "Zieh die Schultern hoch und geh da durch – am {clear_day} wartet die Belohnung.",
            "Streich die Tage ab: Noch {days_until} mal schlafen, dann wird es am {clear_day} schön.",
            "Kein Regen hält ewig. Der {clear_day} bringt das Licht zurück.",
        ],
    },
    
    "carpe_diem": {
        "en": [
            "This is your window. {rain_day} brings rain, so today's sunshine is prime time for getting outside.",
            "The sun is here now, but it's packing for {rain_day}. Don't waste this opportunity.",
            "Clear skies have an expiration date: {rain_day}. Make today count.",
            "Sunshine on borrowed time—{rain_day} takes it back. Get your outdoor tasks done.",
            "The forecast gives you until {rain_day}. That's your deadline for outdoor plans.",
            "Today is the good day. {rain_day} is the wet one. Act accordingly.",
            "This sun won't wait. By {rain_day}, you'll wish you'd used today.",
            "The weather window closes {rain_day}. Today is wide open.",
            "Don't save the sunshine for later—{rain_day} has other plans.",
            "Blue sky today, grey by {rain_day}. If you have outdoor errands, now is the time.",
        ],
        "de": [
            "Das ist dein Zeitfenster. Am {rain_day} kommt der Regen – nutz die Sonne heute unbedingt.",
            "Die Sonne ist da, aber nur auf der Durchreise. Am {rain_day} ist sie weg – verpass die Chance nicht.",
            "Dieser blaue Himmel läuft ab: Stichtag ist der {rain_day}. Mach was draus.",
            "Sonne auf Abruf – am {rain_day} übernimmt wieder das Grau. Erledige heute alles Wichtige draußen.",
            "Die Vorhersage gibt dir eine Frist bis {rain_day}. Bis dahin: Ab nach draußen.",
            "Heute ist der Genießertag, der {rain_day} wird der Regentag. Plan entsprechend.",
            "Das Wetterfenster schließt sich am {rain_day} wieder. Heute steht es noch sperrangelweit offen.",
            "Heb dir die Sonne nicht für später auf – der {rain_day} hat andere Pläne.",
            "Carpe Diem: Schnapp dir das Licht, bevor am {rain_day} die Wolken zurückkehren.",
            "Alles, was du heute an Sonne tankst, hilft dir über den {rain_day} hinweg.",
            "Dringende Empfehlung: Geh raus. Am {rain_day} ist es damit erst mal vorbei.",
            "Ein klassischer Fall von 'Jetzt oder nie'. Warte nicht auf den {rain_day}.",
            "Sammle heute Sonnenstrahlen, du wirst sie am {rain_day} brauchen.",
            "Der Countdown für gutes Wetter läuft und endet am {rain_day}.",
        ],
    },
    
    "warming_trend": {
        "en": [
            "The thermometer is climbing all week—{temp_change}°C warmer by the end. The season is definitely shifting.",
            "Each day this week runs warmer than the last. You can feel the change happening.",
            "The temperature trend is clear: warmer conditions arriving, degree by degree.",
            "Watch the degrees tick up day by day. The cold is losing ground this week.",
            "This week's forecast reads like a warming staircase. {temp_change}°C of progress ahead.",
            "The air is softening. By week's end, you'll notice the difference.",
            "Temperatures are stacking up consistently warmer through the week.",
            "The warming trend is obvious in the forecast. The season is turning.",
        ],
        "de": [
            "Das Thermometer klettert die ganze Woche – am Ende sind es {temp_change}°C mehr. Der Umschwung ist da.",
            "Jeder Tag legt eine Schippe drauf. Man spürt förmlich, wie es wärmer wird.",
            "Der Trend ist eindeutig: Es geht bergauf mit den Temperaturen, Grad für Grad.",
            "Behalt die Temperaturen im Auge – die Kälte verliert diese Woche an Boden.",
            "Die Vorhersage gleicht einer Treppe nach oben: {temp_change}°C Gewinn liegen vor dir.",
            "Die Luft wird milder. Bis zum Wochenende fühlt sich das Wetter ganz anders an.",
            "Konsequent wärmer: Die Temperaturen stapeln sich diese Woche nach oben.",
            "Endlich gute Nachrichten vom Thermometer: Es wird stetig milder.",
            "Die Kälte zieht sich zurück – freu dich auf {temp_change}°C mehr bis Ende der Woche.",
            "Schritt für Schritt wird die Luft angenehmer.",
            "Ein Hauch von Wärme kündigt sich an. Jeden Tag ein bisschen mehr.",
            "Das Wetter schaltet auf 'milder'. Genieße den Anstieg.",
            "Ein schöner Trend: Die Temperaturen klettern aus dem Keller.",
        ],
    },
    
    "cooling_trend": {
        "en": [
            "The week ahead cools down by {temp_change}°C. Time to adjust expectations.",
            "Each day dips a little lower. The season is shifting gears.",
            "The thermometer tells the story: cooler conditions moving in.",
            "Cooler days stack up ahead—{temp_change}°C lower by week's end.",
            "The air is getting crisper. By week's end, layers will be useful.",
            "This week's trend points toward cooler temperatures. Dress accordingly.",
            "The cooling is gradual but consistent through the forecast.",
            "Temperatures drop steadily over the coming days.",
        ],
        "de": [
            "Die Woche bringt Abkühlung: {temp_change}°C gehen runter. Stell dich drauf ein.",
            "Jeden Tag sinkt die Temperatur etwas tiefer. Das Wetter schaltet einen Gang zurück.",
            "Das Thermometer lügt nicht: Frische Luft ist im Anmarsch.",
            "Es wird frischer – bis zum Wochenende fehlen {temp_change}°C im Vergleich zu heute.",
            "Die Luft wird klarer und kälter. Leg dir schon mal den wärmeren Pulli bereit.",
            "Langsam aber sicher kühlt es ab – die Vorhersage lässt da keinen Zweifel.",
            "Mach dich auf frischeres Wetter gefasst.",
            "Es wird Zeit für den Zwiebel-Look – es kühlt merklich ab.",
            "Die Wärme verabschiedet sich vorerst, es wird knackiger.",
            "Bereite dich auf kühlere Tage vor, der Trend ist eindeutig.",
            "Ein Temperatursturz in Raten kommt auf uns zu.",
            "Die milden Tage machen erst mal Pause.",
            "Kühle Luft übernimmt die Regie für den Rest der Woche.",
        ],
    },
    
    "light_fighter": {
        "en": [
            "The clouds are grey, but behind them the sun just got {delta_min} minutes stronger. The light is gaining even when you can't see it.",
            "Grey skies, but here's the reality: you have {delta_min} more minutes of daylight than yesterday. Progress continues regardless of clouds.",
            "Don't let the overcast fool you. The light gained {delta_min} minutes since yesterday—the trend doesn't stop for weather.",
            "The clouds block the view but not the progress: +{delta_min} minutes of daylight today compared to yesterday.",
            "It looks grey out there, but the data shows {delta_min} more minutes of light. The days are lengthening regardless.",
            "Grey today, but the light doesn't stop for clouds. It added {delta_min} minutes anyway.",
            "Behind all that grey, the daylight increased by {delta_min} minutes. The clock keeps moving in your favor.",
            "Overcast skies can't change the astronomy: the day stretched {delta_min} minutes longer than yesterday.",
            "Clouds are temporary. The {delta_min} minutes you gained today are permanent progress.",
            "The sky forgot to be sunny, but it didn't forget to be longer. +{delta_min} minutes.",
        ],
        "de": [
            "Graue Wolken, aber dahinter hat die Sonne {delta_min} Minuten Kraft gewonnen. Das Licht arbeitet für dich, auch unsichtbar.",
            "Der Himmel ist grau, aber Fakt ist: Du hast {delta_min} Minuten mehr Licht als gestern. Der Fortschritt lässt sich nicht aufhalten.",
            "Lass dich vom Grau nicht täuschen. Das Tageslicht hat {delta_min} Minuten zugelegt – der Trend wartet nicht auf schönes Wetter.",
            "Die Wolken versperren die Sicht, aber nicht den Weg: +{delta_min} Minuten Helligkeit im Vergleich zu gestern.",
            "Draußen sieht's trüb aus, aber die Daten lügen nicht: {delta_min} Minuten mehr Licht. Die Tage werden länger, egal was das Wetter macht.",
            "Heute grau, aber das Licht macht keine Pause. Es sind trotzdem {delta_min} Minuten dazugekommen.",
            "Hinter der grauen Fassade ist der Tag um {delta_min} Minuten gewachsen. Die Zeit spielt dir in die Karten.",
            "Wolken können die Astronomie nicht bremsen: Der Tag ist heute {delta_min} Minuten länger.",
            "Wolken sind vergänglich, aber die {delta_min} Minuten Gewinn von heute bleiben dir erhalten.",
            "Der Himmel hat vergessen sonnig zu sein, aber nicht, länger hell zu bleiben. +{delta_min} Minuten für dich.",
            "Das Wetter ist mies, aber die Astronomie ist gut: {delta_min} Minuten mehr Licht als gestern.",
            "Auch wenn man die Sonne nicht sieht – sie arbeitet im Hintergrund und schenkt dir {delta_min} extra Minuten.",
            "Konzentrier dich auf das Positive: Es bleibt abends {delta_min} Minuten länger hell als gestern.",
            "Die Dunkelheit verliert heute wieder {delta_min} Minuten an Boden, Wolken hin oder her.",
            "Vergiss das Grau, feiere das Plus: {delta_min} Minuten mehr Tageslicht.",
            "Lass es regnen, das Licht gewinnt trotzdem: +{delta_min} Minuten heute.",
        ],
    },
    
    "peak_light": {
        "en": [
            "You're at the top of the light curve. These are the longest days the year offers—{day_length} from sunrise to sunset.",
            "Peak daylight is here. Evenings stretch as late as they possibly can.",
            "Maximum daylight: {day_length}. This is the year's peak generosity with light.",
            "These are the apex days—{day_length} of light. It doesn't get more than this.",
            "You're at the year's maximum brightness. {day_length} of daylight today.",
            "Maximum daylight achieved: {day_length}. This is what we waited for through winter.",
            "The sun has topped out at {day_length}. This is as much light as the year gives.",
            "Peak hours: {day_length}. The calendar's maximum light offering.",
        ],
        "de": [
            "Du bist am Gipfel der Lichtkurve angekommen. Das sind die längsten Tage des Jahres – {day_length} Helligkeit pur.",
            "Maximale Helligkeit erreicht. Die Abende dehnen sich jetzt so weit aus, wie es physikalisch möglich ist.",
            "Licht-Rekord: {day_length}. Großzügiger wird das Jahr nicht mehr.",
            "Das sind die Spitzentage – {day_length} Licht am Stück. Mehr geht einfach nicht.",
            "Das Jahresmaximum ist da: {day_length} Tageslicht heute.",
            "Die Sonne gibt alles: {day_length}. Mehr Licht hat das Jahr nicht im Angebot.",
            "Hochsaison fürs Licht: {day_length}. Das absolute Maximum im Kalender.",
            "Genieß es: Länger als heute ({day_length}) scheint die Sonne nicht.",
            "Wir schwimmen im Licht. Mit {day_length} sind wir am absoluten Höhepunkt.",
            "Besser wird's nicht: {day_length} Tageslicht stehen dir heute zur Verfügung.",
            "Das ist der Zenit. {day_length} zwischen Aufgang und Untergang.",
            "Saug das Licht auf – wir haben heute {day_length} davon.",
            "Ein Tag der Superlative: {day_length} Helligkeit.",
            "Es sind die goldenen Tage des Jahres mit {day_length} Lichtdauer.",
        ],
    },
    
    "post_solstice_grind": {
        "en": [
            "The cold is real, but so is this: you've already gained {hours_gained} since the solstice. The turnaround is underway.",
            "Winter's grip feels solid, but the numbers show {hours_gained} more daylight than December's minimum.",
            "It's cold and dark, but you're {hours_gained} ahead of the solstice already. The climb has definitely begun.",
            "January asks for patience and delivers progress: {hours_gained} more light than the darkest day.",
            "The weather says winter. The daylight says recovery: +{hours_gained} since the turning point.",
            "The solstice was the bottom. You've climbed {hours_gained} since then, even if it doesn't feel dramatic yet.",
            "Winter is obvious. The returning light is subtle. But you're already {hours_gained} ahead.",
            "The grind continues, but so does the gain: {hours_gained} of progress since December.",
        ],
        "de": [
            "Die Kälte ist echt, aber der Fortschritt auch: Seit der Sonnenwende hast du schon {hours_gained} Licht gewonnen.",
            "Der Winter hat uns noch fest im Griff, aber wir haben schon {hours_gained} mehr Tageslicht als im tiefsten Dezember.",
            "Es ist kalt, ja. Aber du bist schon {hours_gained} über dem Tiefpunkt. Es geht bergauf.",
            "Der Januar fordert Geduld, gibt aber auch zurück: {hours_gained} mehr Licht als am dunkelsten Tag.",
            "Das Wetter schreit 'Winter', aber das Licht flüstert 'Frühling': +{hours_gained} seit der Wende.",
            "Die Sonnenwende war die Talsohle. Seitdem ging es {hours_gained} nach oben, auch wenn man es kaum merkt.",
            "Der Winter ist offensichtlich, das Licht subtil. Aber der Vorsprung beträgt schon {hours_gained}.",
            "Lass dich nicht unterkriegen: Wir haben schon {hours_gained} Licht zurückerobert.",
            "Ein stiller Erfolg: Das Tageslicht ist um {hours_gained} gewachsen.",
            "Der Weg aus dem Dunkeln ist {hours_gained} lang.",
            "Schritt für Schritt raus aus dem Winter: +{hours_gained} sind geschafft.",
            "Das Schlimmste liegt hinter uns – genau genommen {hours_gained} Lichtstunden.",
            "Sieh es positiv: Wir sind {hours_gained} vom dunkelsten Punkt entfernt.",
            "Die Richtung stimmt wieder: +{hours_gained} auf dem Lichtkonto.",
        ],
    },
    
    "good_streak": {
        "en": [
            "Clear skies today, tomorrow, and beyond—{streak_days} days of good weather ahead. The forecast is cooperating.",
            "This is a genuine stretch of good weather. {streak_days} days of decent conditions ahead.",
            "The forecast shows {streak_days} consecutive good days. That's worth planning around.",
            "A proper run of good weather: {streak_days} days. Streaks like this deserve action.",
            "Day after day of good conditions ahead. {streak_days} days of cooperative weather.",
            "The forecast is consistent: good, good, good. {streak_days} days to work with.",
        ],
        "de": [
            "Klarer Himmel heute, morgen und darüber hinaus – {streak_days} Tage Schönwetter am Stück.",
            "Das ist eine echte Glückssträhne. {streak_days} Tage gute Bedingungen warten auf dich.",
            "Die Vorhersage zeigt {streak_days} gute Tage in Folge. Da kann man was planen.",
            "Eine stabile Schönwetterphase: {streak_days} Tage. So eine Serie muss man nutzen.",
            "Ein Tag schöner als der andere. Das Wetter kooperiert für ganze {streak_days} Tage.",
            "Endlich mal Beständigkeit: Freu dich auf {streak_days} Tage Sonne.",
            "Das Wetter meint es ernst – im positiven Sinne. {streak_days} Tage lang.",
            "Rausgehen ist jetzt Pflicht: Eine Serie von {streak_days} schönen Tagen startet.",
            "Keine Ausreden mehr: {streak_days} Tage Top-Wetter liegen vor dir.",
            "Genieß die Serie: {streak_days} Tage ohne Sorgen beim Blick in den Himmel.",
        ],
    },
    
    "grey_stretch": {
        "en": [
            "The week looks grey throughout—{streak_days} days of clouds ahead. Time to embrace indoor activities.",
            "A stretch of overcast: {streak_days} days. The weather wants you to slow down.",
            "{streak_days} days of grey ahead. Good time for indoor projects.",
            "The forecast is consistent: clouds, clouds, clouds for {streak_days} days.",
            "An extended grey period. Books, projects, and indoor activities.",
            "The sky is taking a break from blue. {streak_days} days of grey ahead.",
        ],
        "de": [
            "Die Woche zeigt sich grau in grau – {streak_days} Tage Wolken. Mach's dir drinnen gemütlich.",
            "Eine echte Grauphase: {streak_days} Tage am Stück. Das Wetter lädt zum Entschleunigen ein.",
            "{streak_days} Tage Grau voraus. Die perfekte Zeit für Projekte in den eigenen vier Wänden.",
            "Die Vorhersage ist leider konstant: Wolken für {streak_days} Tage.",
            "Das Grau bleibt uns erhalten. Zeit für Bücher, Tee und Sofa.",
            "Nimm's gelassen: Es folgen {streak_days} Tage Couch-Wetter.",
            "Die Sonne macht Urlaub, und zwar für {streak_days} Tage.",
            "Stell dich auf {streak_days} Tage Einheitsgrau ein.",
            "Perfektes Wetter, um Dinge zu erledigen: {streak_days} Tage Wolken.",
            "Kuscheldecke raus: Es bleiben {streak_days} Tage grau.",
        ],
    },
    
    "breakthrough_day": {
        "en": [
            "Today breaks the streak. After {bad_days} days of grey, the sun finally shows up.",
            "The waiting paid off. Today is the day the weather remembered to cooperate.",
            "After {bad_days} days of grey, today delivers. The sun is out.",
            "The clouds finally moved on. Today is the breakthrough after {bad_days} grey days.",
            "This is the day the pattern broke. Sun after {bad_days} days of overcast.",
            "The grey streak ends today. After {bad_days} days, the sun returns.",
        ],
        "de": [
            "Heute bricht die Serie. Nach {bad_days} grauen Tagen lässt sich endlich die Sonne blicken.",
            "Das Warten hat ein Ende. Heute spielt das Wetter endlich wieder mit.",
            "Nach {bad_days} Tagen Grau liefert der heutige Tag ab: Sonne satt.",
            "Die Wolken haben aufgegeben. Heute ist der Durchbruch nach {bad_days} Tagen Trübsal.",
            "Endlich ein Musterwechsel. Sonne nach {bad_days} Tagen Bewölkung.",
            "Die Grauphase ist vorbei. Nach {bad_days} Tagen kehrt das Licht zurück.",
            "Atme auf: Die {bad_days} Tage Dunkelheit sind Geschichte.",
            "Belohnung für deine Geduld: Der erste schöne Tag nach {bad_days} miesen.",
            "Schluss mit Grau: Heute ändert sich alles.",
            "Endlich wieder Farbe draußen nach {bad_days} Tagen Schwarz-Weiß.",
        ],
    },
    
    "weekend_good": {
        "en": [
            "The weekend forecast looks solid. Saturday and Sunday both show good conditions for outdoor plans.",
            "Good news for the weekend: clear skies on both days. Plan something outside.",
            "The forecast saved the good weather for the weekend. Saturday and Sunday both look decent.",
            "Your weekend looks workable. Outdoor plans are reasonable to make.",
            "Saturday and Sunday both look favorable. Good timing for outdoor activities.",
        ],
        "de": [
            "Die Wochenend-Prognose sieht stabil aus. Samstag und Sonntag bieten gute Bedingungen.",
            "Gute Nachrichten fürs Wochenende: Klarer Himmel an beiden Tagen. Nichts wie raus!",
            "Die Vorhersage hat sich das gute Wetter fürs Wochenende aufgehoben. Sieht gut aus.",
            "Dein Wochenende wird brauchbar. Pläne für draußen kannst du definitiv machen.",
            "Samstag und Sonntag zeigen sich von ihrer besten Seite. Perfektes Timing.",
            "Freu dich aufs Wochenende: Das Wetter spielt an beiden Tagen mit.",
            "Endlich mal ein Wochenende, an dem man was unternehmen kann.",
            "Das Wochenende wird schön – nutz die freien Tage.",
        ],
    },
    
    "weekend_bad": {
        "en": [
            "The weekend looks wet. Indoor plans might be the smarter choice.",
            "Rain on Saturday, more on Sunday. The weekend is an indoor one.",
            "The forecast suggests a cozy weekend—clouds and rain throughout.",
            "The weekend weather isn't cooperating. Time for indoor alternatives.",
            "Grey skies for Saturday and Sunday. The week ends quietly indoors.",
        ],
        "de": [
            "Das Wochenende wird nass. Such dir lieber was für drinnen.",
            "Regen am Samstag, noch mehr am Sonntag. Ein klassisches Couch-Wochenende.",
            "Die Vorhersage deutet auf Gemütlichkeit hin – Wolken und Regen durchgehend.",
            "Das Wetter am Wochenende streikt. Zeit für Plan B in der Wohnung.",
            "Grauer Himmel am Samstag und Sonntag. Die Woche endet ruhig.",
            "Mach's dir zuhause schön, draußen wird es ungemütlich.",
            "Ein Wochenende zum Ausschlafen und Lesen – draußen verpasst du nichts.",
            "Das Wochenende wird leider verregnet.",
        ],
    },
    
    "stable_focus_light": {
        "en": [
            "The weather is steady and unremarkable—which puts the focus on the light: {day_length} of daylight today.",
            "Nothing dramatic in the forecast. Just the quiet progress of {delta_min} more minutes per day.",
            "Stable conditions mean the real story is the daylight: {day_length} and changing.",
            "The weather is background. The light—{day_length}—is the actual news.",
            "Uneventful skies. That leaves room to notice you have {day_length} of daylight today.",
        ],
        "de": [
            "Das Wetter ist unspektakulär – umso mehr rückt das Licht in den Fokus: {day_length} heute.",
            "Nichts Dramatisches in der Vorhersage. Nur der stille Fortschritt von {delta_min} Minuten täglich.",
            "Stabiles Wetter heißt: Die eigentliche Story ist das Tageslicht ({day_length}).",
            "Das Wetter ist Nebensache. Das Licht – satte {day_length} – ist die eigentliche News.",
            "Ruhiger Himmel. Das gibt Raum zu bemerken: Du hast heute {day_length} Licht.",
            "Keine Wetterkapriolen, dafür verlässliches Licht: {day_length} lang.",
            "Wenn das Wetter langweilig ist, zählt die Tageslänge: {day_length}.",
            "Ein ruhiger Tag, an dem das Licht die Hauptrolle spielt.",
        ],
    },
    
    "spring_acceleration": {
        "en": [
            "This is the fast phase. The light is gaining {delta_min} minutes daily—the steepest climb of the year.",
            "The daylight is increasing quickly now: +{delta_min} minutes per day. You can see the evenings stretching.",
            "The acceleration is measurable. {delta_min} minutes daily means visible change week to week.",
            "This is when waiting turns to momentum. +{delta_min} minutes each day adds up fast.",
            "The daylight gains are at their maximum now: {delta_min} minutes daily.",
        ],
        "de": [
            "Das ist die Überholspur. Das Licht gewinnt täglich {delta_min} Minuten – steiler geht's nicht.",
            "Es geht rasant aufwärts: +{delta_min} Minuten pro Tag. Die Abende werden förmlich länger gezogen.",
            "Die Beschleunigung ist enorm. {delta_min} Minuten täglich bedeuten sichtbare Veränderung jede Woche.",
            "Jetzt kommt Schwung in die Sache. +{delta_min} Minuten jeden Tag summieren sich schnell.",
            "Vollgas Richtung Sommer: Wir gewinnen {delta_min} Minuten jeden einzelnen Tag.",
            "Spürst du das Tempo? Jeden Tag {delta_min} Minuten mehr Licht.",
            "Das ist der Turbo-Gang des Jahres: +{delta_min} Minuten.",
            "Schneller werden die Tage nicht mehr länger: {delta_min} Minuten Zuwachs.",
        ],
    },
    
    "solstice_approaching": {
        "en": [
            "The solstice is {days_to_solstice} days away. You're in the final approach to the year's turning point.",
            "Only {days_to_solstice} days until the solstice. The light is almost at its {peak_or_min}.",
            "The solstice approaches: {days_to_solstice} days. The year is about to pivot.",
            "We're in solstice territory—just {days_to_solstice} days from the astronomical milestone.",
            "The countdown is on: {days_to_solstice} days until the year turns.",
        ],
        "de": [
            "Die Sonnenwende ist nur noch {days_to_solstice} Tage entfernt. Endanflug auf den Wendepunkt.",
            "Nur noch {days_to_solstice} Tage bis zur Wende. Das Licht ist fast am {peak_or_min}.",
            "Der Countdown läuft: {days_to_solstice} Tage bis sich das Jahr dreht.",
            "Bald ist es soweit: In {days_to_solstice} Tagen ist Sonnenwende.",
            "Das große Ereignis steht bevor: noch {days_to_solstice} Tage.",
            "Wir zählen die Tage: Nur noch {days_to_solstice} bis zur Wende.",
            "Fast geschafft: {days_to_solstice} Tage trennen uns vom Wendepunkt.",
            "Merk dir das Datum, in {days_to_solstice} Tagen ändert sich die Richtung.",
        ],
    },
}


# ===== SEASONAL PHASE DESCRIPTIONS =====
SEASONAL_PHASE = {
    "deep_winter": {
        "en": [
            "This is January's deal: cold outside, but the light account is already growing.",
            "Deep winter has settled in, but the solstice already happened—the days are getting longer.",
            "The coldest weeks coincide with the start of light recovery. The pattern has already reversed.",
            "January's weather doesn't match its astronomy: the harshest cold comes after the light starts returning.",
            "Winter at its coldest, but astronomically we're already past the lowest point.",
        ],
        "de": [
            "Der Winter sitzt tief, aber die Sonnenwende ist durch – die Tage strecken sich wieder.",
            "Die kältesten Wochen treffen auf die Rückkehr des Lichts. Die Wende ist längst passiert.",
            "Das Wetter hinkt der Astronomie hinterher: Die Kälte kommt, wenn das Licht schon zurückkehrt.",
            "Tiefster Winter gefühlt, aber astronomisch ist das Schlimmste vorbei.",
            "Lass dich von der Kälte nicht täuschen, das Licht kommt zurück.",
            "Der Winter zeigt Zähne, aber die Sonne holt auf.",
            "Wir stecken mitten im Winter, aber der Weg führt Richtung Licht.",
            "Kalt, aber hoffnungsvoll: Die Tage werden wieder länger.",
        ],
    },
    "late_winter": {
        "en": [
            "Late winter shows real momentum now—daylight gains are accelerating noticeably.",
            "February's energy comes from knowing change is close and visible.",
            "This is the sprint phase: daylight gains accelerate toward the equinox.",
            "Late winter delivers evidence. The light proves change is coming.",
            "The push toward spring is obvious now. The light is moving fast.",
        ],
        "de": [
            "Die Energie des Februars: Man spürt, dass der Wandel nah ist.",
            "Sprintphase: Wir rasen auf die Tagundnachtgleiche zu.",
            "Der Schub Richtung Frühling ist unübersehbar. Das Licht macht Tempo.",
            "Es geht voran, und zwar schnell. Der Winter muss weichen.",
            "Jeden Tag ein bisschen mehr Frühling in der Luft.",
            "Das Licht drückt aufs Gaspedal.",
            "Es ist nicht mehr zu übersehen: Die dunkle Zeit endet.",
            "Der Februar macht ernst mit dem Frühling.",
        ],
    },
    "early_spring": {
        "en": [
            "The equinox is behind you. Days now outlast nights—the balance has shifted.",
            "Early spring is the exhale after winter. Light wins from here.",
            "You're in the bright half of the year now. That's the astronomy.",
            "Spring's arrival is official. The light proves what the weather sometimes denies.",
            "The equinox marked the turn. You're on the generous side of the calendar now.",
        ],
        "de": [
            "Die Tagundnachtgleiche liegt hinter uns. Die Tage sind jetzt länger als die Nächte.",
            "Frühling heißt Aufatmen nach dem Winter. Ab jetzt gewinnt das Licht.",
            "Willkommen in der hellen Jahreshälfte.",
            "Der Frühling ist offiziell. Das Licht beweist, was das Wetter vielleicht noch leugnet.",
            "Die Wende ist geschafft. Wir sind auf der Sonnenseite des Kalenders.",
            "Die Dunkelheit hat verloren, die Tage dominieren.",
            "Endlich mehr Licht als Schatten.",
            "Das große Aufwachen hat begonnen.",
            "Genieß das Plus an Helligkeit, es gehört jetzt uns.",
        ],
    },
    "late_spring": {
        "en": [
            "Late spring is the approach to peak light. The longest days are near.",
            "You're climbing toward the summit. Maximum light is weeks away.",
            "Late spring offers some of the best light conditions of the year.",
            "The climb toward summer solstice continues. Each day adds more.",
            "This is the phase where light is abundant. The peak is close.",
        ],
        "de": [
            "Später Frühling: Der Anflug auf das Licht-Maximum. Die längsten Tage sind greifbar.",
            "Wir klettern Richtung Gipfel. Das maximale Licht ist nur noch Wochen entfernt.",
            "Der Aufstieg zur Sommersonnenwende läuft. Jeden Tag ein Stückchen mehr.",
            "Es wird kaum noch dunkel.",
            "Wir baden förmlich in Tageslicht.",
            "Die Vorfreude auf den längsten Tag steigt.",
            "Helligkeit satt – das ist der späte Frühling.",
            "Jeden Abend bleibt es länger hell.",
        ],
    },
    "peak_summer": {
        "en": [
            "You're at the top. The year offers no longer day than these.",
            "Peak summer is the summit. From here, the only way is gently down.",
            "The longest days of the year are now. This is what the climb was for.",
            "Summer solstice territory: maximum light, maximum evening.",
            "You're standing at the peak of the light cycle.",
        ],
        "de": [
            "Ganz oben angekommen. Länger werden die Tage nicht mehr.",
            "Das sind die längsten Tage. Dafür haben wir den Winter durchgestanden.",
            "Sonnenwende-Territorium: maximales Licht, endlose Abende.",
            "Du stehst auf der Spitze des Lichtzyklus.",
            "Mehr Sommer geht nicht.",
            "Die Nächte sind nur noch kurze Pausen.",
            "Genieß den Höchststand der Sonne.",
            "Das Licht feiert seinen Triumph.",
            "Es sind die Tage, die nie enden wollen.",
            "Nutze die langen Abende, sie gehören dir.",
        ],
    },
    "late_summer": {
        "en": [
            "Late summer is the slow decline. Still bright, but the peak is behind you.",
            "The days are noticeably shorter than at the solstice, but still generous.",
            "Late summer is abundance with awareness. The light is receding.",
            "You're past the peak, but the descent is gentle. Summer lingers.",
            "The retreat from maximum light is underway, but slow.",
        ],
        "de": [
            "Spätsommer heißt Fülle mit Bewusstsein.",
            "Der Höhepunkt ist vorbei, aber der Sommer bleibt noch.",
            "Der Rückzug vom Maximum läuft, aber ganz gemächlich.",
            "Goldenes Licht und lange Abende.",
            "Der Sommer reift, das Licht wird wärmer.",
            "Genieß die Reste des langen Lichts.",
            "Es wird früher dunkel, aber es ist noch schön.",
            "Ein sanftes Ausklingen der hellen Jahreszeit.",
            "Die Abende sind immer noch ein Geschenk.",
        ],
    },
    "early_autumn": {
        "en": [
            "The equinox signals the shift. Nights now outlast days.",
            "Early autumn is the mirror of early spring—steep change, opposite direction.",
            "You've crossed into the dark half of the year. The nights are winning now.",
            "The descent accelerates through autumn. Each week is noticeably shorter.",
            "Early autumn is when the loss becomes obvious. Sunset comes earlier fast.",
        ],
        "de": [
            "Die Tagundnachtgleiche signalisiert den Wechsel. Die Nächte sind jetzt länger.",
            "Willkommen in der dunklen Jahreshälfte. Die Nächte übernehmen die Führung.",
            "Der Abstieg beschleunigt sich. Jede Woche wird spürbar kürzer.",
            "Es wird gemütlicher, aber auch dunkler.",
            "Die Balance kippt zur Dunkelheit.",
            "Der Herbst macht ernst: Kurze Tage voraus.",
            "Abschied vom langen Licht.",
            "Der Wandel ist jetzt nicht mehr zu leugnen.",
        ],
    },
    "late_autumn": {
        "en": [
            "Late autumn is the final approach to the year's minimum. The solstice is near.",
            "You're descending toward the bottom, but the turning point is in sight.",
            "Late autumn is the last stretch of darkness before the turnaround.",
            "The shortest days approach. Late autumn is the valley before the climb.",
            "November brings you close to the minimum. The solstice waits ahead.",
        ],
        "de": [
            "Spätherbst ist der Endanflug aufs Jahresminimum. Die Sonnenwende ist nah.",
            "Wir steigen zum Tiefpunkt ab, aber der Wendepunkt ist schon in Sicht.",
            "Die kürzesten Tage kommen. Das ist das Tal vor dem nächsten Aufstieg.",
            "Der November bringt uns nah ans Minimum. Bald geht's wieder aufwärts.",
            "Durchhalten, die Wende ist nicht mehr weit.",
            "Es wird dunkel, aber bald kehrt das Licht zurück.",
            "Die Zielgerade zum kürzesten Tag.",
            "Nur noch ein bisschen tiefer, dann kommt die Wende.",
        ],
    },
}


# ===== NATURE SIGNS BY MONTH =====
NATURE_SIGNS = {
    1: {
        "en": [
            "On clear winter days, watch for robins—they're more visible now and singing from exposed perches.",
            "If you have a bird feeder, clear cold days bring the most visitors.",
            "Hazel catkins are worth watching. When they lengthen and turn yellow, spring is loading.",
            "Days are now gaining light at an accelerating rate.",
            "Winter rain brings earthworms to the surface. That's why blackbirds patrol lawns.",
        ],
        "de": [
            "An klaren Wintertagen: Halt nach Rotkehlchen Ausschau – sie singen jetzt gut sichtbar von ganz oben.",
            "Am Vogelhäuschen herrscht Hochbetrieb, besonders an klaren, kalten Tagen.",
            "Achte auf Haselkätzchen: Wenn sie lang und gelb werden, wird der Frühling geladen.",
            "Die Tage gewinnen jetzt immer schneller an Licht.",
            "Hör genau hin: Manche Vögel üben schon für den Frühling.",
            "Auch im tiefsten Winter gibt es Leben zu entdecken.",
            "Die Natur schläft nicht, sie ruht nur.",
            "Such nach den ersten Anzeichen des Erwachens.",
        ],
    },
    2: {
        "en": [
            "Snowdrops are fully out now. They're the reliable first flower—check churchyards and old gardens.",
            "On sunny February days, watch for bumblebee queens searching for nest sites.",
            "Birdsong intensifies in February. Great tits and robins are getting louder.",
            "Trees are visibly preparing. Buds are swelling on everything.",
            "February feels like waiting, but the activity underneath is intense. Life is loading.",
        ],
        "de": [
            "Schneeglöckchen sind da. Die verlässlichen ersten Boten.",
            "An sonnigen Februartagen suchen dicke Hummelköniginnen schon nach Nistplätzen.",
            "Der Vogelgesang schwillt an. Kohlmeisen und Rotkehlchen werden lauter.",
            "Die Bäume machen sich bereit: Überall schwellen die Knospen.",
            "Februar fühlt sich an wie Warten, aber unter der Oberfläche brodelt das Leben.",
            "Der Frühling klopft leise an.",
            "Halte Ausschau nach den ersten Farbtupfern im Grau.",
            "Die Vögel wissen es schon: Es geht bald los.",
            "Jeden Tag erwacht ein bisschen mehr.",
        ],
    },
    3: {
        "en": [
            "Daffodils are out now—wild ones in woods, cultivated ones everywhere else.",
            "The dawn chorus is significant now. Blackbirds and song thrushes sing before sunrise.",
            "Wild garlic starts to appear in woodlands. You smell it before you see it.",
            "March is the month of visible acceleration. Everything happens at once.",
            "The equinox means days longer than nights from here. The dark half is over.",
        ],
        "de": [
            "Narzissen blühen – wilde im Wald, die anderen in den Gärten.",
            "Das Morgenkonzert ist jetzt laut. Amseln und Drosseln singen schon vor Sonnenaufgang.",
            "Bärlauchzeit im Wald. Der Duft verrät ihn, bevor du ihn siehst.",
            "März ist der Monat der Beschleunigung. Alles explodiert gleichzeitig.",
            "Tagundnachtgleiche: Ab jetzt sind die Tage länger als die Nächte.",
            "Der Wald wird grün und laut.",
            "Es riecht nach Erde und Wachstum.",
            "Die Natur gibt Vollgas.",
        ],
    },
    4: {
        "en": [
            "April sun on cherry blossom is one of the best sights of the year.",
            "The dawn chorus is intense now. Get up early—the singing starts before 5 AM.",
            "Butterflies are everywhere now: orange tips, peacocks, small whites.",
            "The smell of blossom is pervasive. Apple, cherry, hawthorn.",
            "The warmth is becoming reliable now. April evenings are mild.",
        ],
        "de": [
            "Aprilsonne auf Kirschblüten – viel schöner wird's nicht.",
            "Das Morgenkonzert hat Hochsaison. Früh aufstehen lohnt sich.",
            "Die Schmetterlinge sind los: Aurorafalter und Tagpfauenaugen überall.",
            "Es duftet nach Blüten: Apfel, Kirsche, Weißdorn.",
            "Die Wärme bleibt jetzt. Aprilabende sind oft schon mild.",
            "Die Welt wird bunt.",
            "Alles summt und brummt.",
            "Der schönste Monat zum Spazierengehen.",
            "Genieß das Erwachen.",
        ],
    },
    5: {
        "en": [
            "May warmth brings butterflies in clouds. Painted ladies, commas, and whites.",
            "Swifts are fully present now, screaming through evening skies.",
            "Clear May evenings are long and warm. Sunset comes after 9 PM now.",
            "May is the month of abundance. Everything is growing, flowering, or nesting.",
            "May brings the sense that summer is actually here, not just coming.",
        ],
        "de": [
            "Die Maiwärme bringt Schmetterlingswolken. Distelfalter und Weißlinge tanzen.",
            "Die Mauersegler sind zurück und jagen schreiend durch den Abendhimmel.",
            "Klare Maiabende sind lang und warm. Sonnenuntergang erst nach 21 Uhr.",
            "Mai ist Überfluss. Alles wächst, blüht und brütet.",
            "Im Mai fühlt man: Der Sommer ist wirklich da, nicht nur versprochen.",
            "Das Leben tobt draußen.",
            "Alles ist grün und saftig.",
            "Lange Abende, laue Luft.",
        ],
    },
    6: {
        "en": [
            "The summer solstice approaches—these are nearly the longest days of the year.",
            "June evenings are the longest. Sunset after 9:30 PM gives hours of usable light.",
            "Swifts are everywhere, feeding hard for breeding.",
            "June is the month of maximum light. Use it.",
            "The year's peak light deserves attention. Notice how late the twilight lasts.",
        ],
        "de": [
            "Die Sommersonnenwende naht – wir haben fast die längsten Tage.",
            "Juniabende sind endlos. Sonne bis nach halb zehn.",
            "Mauersegler sind überall und jagen Futter für den Nachwuchs.",
            "Juni ist der Licht-Monat schlechthin. Kost ihn aus.",
            "Helle Nächte, kurze Dunkelheit.",
            "Der Sommer in Hochform.",
            "Draußen sein bis in die Nacht.",
            "Das Licht scheint ewig.",
            "Maximale Energie.",
        ],
    },
    7: {
        "en": [
            "Lavender and buddleia are butterfly magnets. Watch for peacocks and red admirals.",
            "Clear July evenings are warm enough to sit out until 10 PM.",
            "July is the month when summer feels fully arrived. The heat is real.",
            "The days are shortening, but imperceptibly. You won't notice yet.",
            "July warmth lingers into evening. Sitting outside is comfortable until dark.",
        ],
        "de": [
            "Lavendel und Sommerflieder ziehen Schmetterlinge magisch an.",
            "Juliabende sind warm genug, um bis 22 Uhr im T-Shirt draußen zu sitzen.",
            "Im Juli ist der Sommer etabliert. Die Hitze steht.",
            "Die Wärme hält sich bis spät abends. Draußen sitzen ist herrlich.",
            "Hochsommer-Gefühle.",
            "Zirpen und Summen überall.",
            "Die Luft flirrt.",
            "Ein Monat zum Genießen.",
            "Sommer satt.",
        ],
    },
    8: {
        "en": [
            "Blackberries are fully ripe now. The picking season is at its peak.",
            "Clear August days have a golden quality. The light is aging toward autumn.",
            "August is the harvest month. The work of the year comes to fruition.",
            "Days are noticeably shorter than July. The change is measurable now.",
            "August has a melancholy edge. The abundance is real, but temporary.",
        ],
        "de": [
            "Brombeeren sind reif. Naschen erlaubt.",
            "Augusttage haben dieses goldene Licht. Der Herbst kündigt sich leise an.",
            "August ist Erntezeit. Die Natur liefert ab.",
            "Die Tage sind spürbar kürzer als im Juli.",
            "Der Sommer wird reifer.",
            "Goldene Stunden am Abend.",
            "Genieß die Ernte.",
            "Spätsommer-Magie.",
        ],
    },
    9: {
        "en": [
            "September sun on turning leaves is the start of the color show.",
            "Clear September days are harvest days. Apples, pears, plums are ready.",
            "September is the transition month. Summer ends, autumn begins.",
            "The equinox means nights now exceed days. The dark half starts.",
            "Days shorten rapidly now. The rate of change matches spring in reverse.",
        ],
        "de": [
            "Septembersonne auf bunten Blättern – die Show beginnt.",
            "Erntezeit für Äpfel, Birnen und Pflaumen.",
            "September ist Übergang. Tschüss Sommer, hallo Herbst.",
            "Tagundnachtgleiche: Die Nächte gewinnen die Oberhand.",
            "Die Tage werden rasant kürzer.",
            "Frische Luft und warme Farben.",
            "Wandel liegt in der Luft.",
            "Die Natur zieht sich langsam zurück.",
            "Herbstbeginn.",
        ],
    },
    10: {
        "en": [
            "October sun on peak autumn color is one of the year's great sights.",
            "Clear October days are cold but beautiful. The light is precious.",
            "October is the main month for autumn color.",
            "Clocks change at month's end—evenings suddenly darker.",
            "Days shorten rapidly. The change is visible week to week.",
        ],
        "de": [
            "Oktobersonne auf Herbstlaub – einfach herrlich.",
            "Kalte, klare Oktobertage haben ein kostbares Licht.",
            "Jetzt glühen die Bäume in allen Farben.",
            "Achtung Zeitumstellung: Abends wird's schlagartig dunkel.",
            "Indian Summer vor der Haustür.",
            "Raschelndes Laub und goldene Sonne.",
            "Der Herbst zieht alle Register.",
            "Genieß die letzten warmen Strahlen.",
            "Kuschelzeit beginnt.",
        ],
    },
    11: {
        "en": [
            "November sun is precious. The bare trees don't block it, at least.",
            "Clear November days are cold but bright. The light is rationed.",
            "November is the month of bare trees and short days.",
            "Days are short and getting shorter. The solstice is next month.",
            "Grey November is the archetype. This is what the month often delivers.",
        ],
        "de": [
            "Novembersonne ist selten und kostbar. Gut, dass die Bäume kahl sind.",
            "Klar, kalt, hell – aber kurz. Das Novemberlicht.",
            "November: Kahle Äste, kurze Tage.",
            "Es geht auf das Minimum zu. Sonnenwende im Blick.",
            "Stille Zeit.",
            "Nebel und Ruhe.",
            "Die Natur schläft ein.",
            "Lichtblicke suchen.",
        ],
    },
    12: {
        "en": [
            "December sun is scarce but valuable. Every minute of direct light counts.",
            "The solstice approaches—the shortest day, the turning point.",
            "December sun stays low all day. A constant golden-hour quality.",
            "After the solstice, days lengthen. The psychological boost is real.",
            "December is the bottom of the light cycle. The only way is up.",
        ],
        "de": [
            "Dezembersonne ist rar. Jede Minute zählt.",
            "Kürzester Tag voraus. Der Wendepunkt naht.",
            "Die Sonne steht tief.",
            "Nach der Wende geht's aufwärts. Ein gutes Gefühl.",
            "Dunkle Tage, helle Lichter.",
            "Warten auf die Wende.",
            "Tiefwinter-Stimmung.",
            "Jeder Sonnenstrahl ist ein Geschenk.",
            "Bald wird es wieder heller.",
        ],
    },
}


# ===== GENERAL NATURE FACTS =====
NATURE_FACTS_GENERAL = {
    "en": [
        "Bird feeders see more activity on cold days. The energy demand increases.",
        "Robins sing year-round. One of the few birds that holds winter territory.",
        "The smell of the season is as diagnostic as the temperature.",
        "Morning mist burns off when temperatures rise. Watch the process happen.",
        "Seasons are caused by Earth's tilt, not its distance from the sun.",
    ],
    "de": [
        "An kalten Tagen ist am Futterhaus die Hölle los. Energiebedarf steigt.",
        "Rotkehlchen singen immer. Sie verteidigen ihr Revier auch im Winter.",
        "Morgennebel verschwindet mit der Wärme. Ein schönes Schauspiel.",
        "Die Natur hat ihren eigenen Rhythmus.",
        "Achte auf die kleinen Veränderungen draußen.",
        "Tiere wissen genau, was das Wetter macht.",
        "Draußen gibt es immer was zu sehen.",
        "Verbinde dich mit der Jahreszeit.",
    ],
}


# ===== CLOSINGS =====
CLOSINGS = {
    "practical": {
        "en": ["Plan accordingly.", "Adjust as needed.", "Good to know for planning."],
        "de": [
            "Plan entsprechend.", 
            "Gut zu wissen.",
            "Richte dich darauf ein.",
        ],
    },
    "observational": {
        "en": ["Worth paying attention to.", "Something to notice.", "The details matter."],
        "de": [
            "Einfach mal beobachten.", 
            "Schau genau hin.",
            "Halt die Augen offen.",
        ],
    },
    "simple": {
        "en": ["That's the picture.", "Those are the facts.", "There it is."],
        "de": [
            "Das sind die Fakten.", 
            "Kurz und knapp.",
            "So sieht's aus.",
        ],
    },
}


# ===== DAYLIGHT FACTS TEMPLATES =====
DAYLIGHT_FACTS = {
    "en": [
        "Today you have {day_length} of daylight, running from {sunrise} to {sunset}.",
        "The day runs {day_length}, with sunrise at {sunrise} and sunset at {sunset}.",
        "Daylight today: {day_length}. The sun is up from {sunrise} to {sunset}.",
        "You're working with {day_length} of light today, {sunrise} to {sunset}.",
    ],
    "de": [
        "Heute hast du {day_length} Tageslicht, von {sunrise} bis {sunset}.",
        "Der Tag bringt dir {day_length} Licht – Aufgang {sunrise}, Untergang {sunset}.",
        "Lichtbilanz heute: {day_length}. Sonne von {sunrise} bis {sunset}.",
        "{day_length} Helligkeit stehen dir heute zur Verfügung ({sunrise} bis {sunset}).",
        "Zwischen {sunrise} und {sunset} ist es hell – insgesamt {day_length}.",
        "Lichtdauer heute: {day_length}.",
        "Von {sunrise} bis {sunset} regiert die Sonne ({day_length}).",
    ],
}


# ===== DELTA PHRASES =====
DELTA_PHRASES = {
    "gaining": {
        "en": [
            "That's {delta} minutes more than yesterday.",
            "You gained {delta} minutes compared to yesterday.",
            "+{delta} minutes versus yesterday.",
        ],
        "de": [
            "Das sind {delta} Minuten mehr als gestern.",
            "Du hast {delta} Minuten im Vergleich zu gestern gewonnen.",
            "+{delta} Minuten gegenüber gestern.",
            "Der Tag ist um {delta} Minuten gewachsen.",
        ],
    },
    "losing": {
        "en": [
            "That's {delta} minutes less than yesterday.",
            "You lost {delta} minutes compared to yesterday.",
            "{delta} minutes shorter than yesterday.",
        ],
        "de": [
            "Das sind {delta} Minuten weniger als gestern.",
            "Du hast {delta} Minuten im Vergleich zu gestern verloren.",
            "{delta} Minuten kürzer als gestern.",
            "Der Tag ist um {delta} Minuten geschrumpft.",
        ],
    },
}