"""
Dynamic content library for Seasonal Horizon.
Narrative-driven, scenario-based content with extensive variety.
Focus on concrete nature observations and practical information.
"""

# ===== FORECAST NARRATIVES =====
FORECAST_NARRATIVES = {
    "rain_clearing_soon": [
        "Grey skies today, but the forecast shows {clear_day} breaking through—just {days_until} more days to wait.",
        "The rain is temporary. By {clear_day}, the clouds lift and you'll have your moment in the sun.",
        "Hold steady through the grey. {clear_day} brings the clearing you're waiting for.",
        "This wet stretch has an end date: {clear_day}. Mark your calendar.",
        "Today's drizzle is just weather passing through. {clear_day}'s sunshine is coming.",
        "The clouds are visitors, not residents. They leave by {clear_day}.",
        "Patience pays: {days_until} days of grey, then {clear_day} delivers clear skies.",
        "Rain now, but I can see {clear_day} on the forecast—good conditions are coming.",
        "Every rainy streak has its last day. This one ends before {clear_day}.",
        "Wet windows today, but {clear_day} is circled on the weather chart.",
        "The rain is finishing its work. By {clear_day}, it moves on and you can get outside.",
        "Think of today's clouds as the setup for {clear_day}'s payoff.",
        "The barometer is already trending toward {clear_day}. Plan for it.",
        "Grey now, but {clear_day} looks solid for outdoor activities.",
        "Weather systems move through. This one clears by {clear_day}.",
    ],
    
    "carpe_diem": [
        "This is your window. {rain_day} brings rain, so today's sunshine is prime time for getting outside.",
        "The sun is here now, but it's packing for {rain_day}. Don't waste this opportunity.",
        "Clear skies have an expiration date: {rain_day}. Make today count.",
        "Sunshine on borrowed time—{rain_day} takes it back. Get your outdoor tasks done.",
        "The forecast gives you until {rain_day}. That's your deadline for outdoor plans.",
        "Today is the good day. {rain_day} is the wet one. Act accordingly.",
        "This sun won't wait. By {rain_day}, you'll wish you'd used today.",
        "The weather window closes {rain_day}. Today is wide open for whatever you need.",
        "Don't save the sunshine for later—{rain_day} has other plans.",
        "Blue sky today, grey by {rain_day}. If you have outdoor errands, now is the time.",
        "The sun is giving you {days_until} days of grace. Use them well.",
        "Today's light is a gift with a timer. {rain_day} stops the clock.",
        "The forecast says move now. {rain_day} says you can't.",
        "Sun now, umbrellas by {rain_day}. Priorities are clear.",
        "If you've been putting off outdoor activities, today through {rain_day} is your chance.",
    ],
    
    "warming_trend": [
        "The thermometer is climbing all week—{temp_change}°C warmer by the end. The season is definitely shifting.",
        "Each day this week runs warmer than the last. You can feel the change happening.",
        "The temperature trend is clear: warmer conditions arriving, degree by degree.",
        "Watch the degrees tick up day by day. The cold is losing ground this week.",
        "This week's forecast reads like a warming staircase. {temp_change}°C of progress ahead.",
        "The air is softening. By week's end, you'll notice the difference.",
        "Temperatures are stacking up consistently warmer through the week.",
        "The warming trend is obvious in the forecast. The season is turning.",
        "Every degree this week pushes us closer to milder conditions.",
        "The forecast shows a clear upward line. That's real seasonal change.",
        "Warmth is accumulating. The week ahead adds {temp_change}°C to the baseline.",
        "The cold is retreating day by day, degree by degree.",
        "This is what a seasonal transition looks like in the numbers.",
        "The week builds toward noticeably warmer conditions.",
        "Warming trend confirmed: expect milder temperatures through the week.",
    ],
    
    "cooling_trend": [
        "The week ahead cools down by {temp_change}°C. Time to adjust expectations.",
        "Each day dips a little lower. The season is shifting gears.",
        "The thermometer tells the story: cooler conditions moving in.",
        "Cooler days stack up ahead—{temp_change}°C lower by week's end.",
        "The air is getting crisper. By week's end, layers will be useful.",
        "This week's trend points toward cooler temperatures. Dress accordingly.",
        "The cooling is gradual but consistent through the forecast.",
        "Temperatures drop steadily over the coming days.",
        "The forecast shows a downward trend: {temp_change}°C cooler ahead.",
        "Cooler weather is settling in for the week.",
        "The temperature curve bends downward. Pack a jacket.",
        "Each day this week runs a bit cooler than the one before.",
        "The week cools off progressively—plan for it.",
        "This is the weather adjusting to the season. Cooler days ahead.",
        "The trend is clear—temperatures dropping through the week.",
    ],
    
    "light_fighter": [
        "The clouds are grey, but behind them the sun just got {delta_min} minutes stronger. The light is gaining even when you can't see it.",
        "Grey skies, but here's the reality: you have {delta_min} more minutes of daylight than yesterday. Progress continues regardless of clouds.",
        "Don't let the overcast fool you. The light gained {delta_min} minutes since yesterday—the trend doesn't stop for weather.",
        "The clouds block the view but not the progress: +{delta_min} minutes of daylight today compared to yesterday.",
        "It looks grey out there, but the data shows {delta_min} more minutes of light. The days are lengthening regardless.",
        "Grey today, but the light doesn't stop for clouds. It added {delta_min} minutes anyway.",
        "Behind all that grey, the daylight increased by {delta_min} minutes. The clock keeps moving in your favor.",
        "Overcast skies can't change the astronomy: the day stretched {delta_min} minutes longer than yesterday.",
        "Clouds are just atmosphere. The {delta_min} minutes of extra light is the real story.",
        "Clouds are temporary. The {delta_min} minutes you gained today are permanent progress.",
        "The sky forgot to be sunny, but it didn't forget to be longer. +{delta_min} minutes.",
        "Even grey days add up. This one added {delta_min} minutes to your light budget.",
        "The weather varies. The daylight gain doesn't. +{delta_min} minutes today.",
        "Don't judge the day by its color. Judge it by the {delta_min} minutes it gave you.",
        "The clouds are what you see. The {delta_min} extra minutes are what's actually happening.",
    ],
    
    "peak_light": [
        "You're at the top of the light curve. These are the longest days the year offers—{day_length} from sunrise to sunset.",
        "Peak daylight is here. Evenings stretch as late as they possibly can.",
        "Maximum daylight: {day_length}. This is the year's peak generosity with light.",
        "These are the apex days—{day_length} of light. It doesn't get more than this.",
        "You're at the year's maximum brightness. {day_length} of daylight today.",
        "Maximum daylight achieved: {day_length}. This is what we waited for through winter.",
        "The sun has topped out at {day_length}. This is as much light as the year gives.",
        "Peak hours: {day_length}. The calendar's maximum light offering.",
        "This is the plateau at the top. The longest evenings of the year.",
        "The climb is complete. You're at the summit of the light cycle with {day_length}.",
        "These days deliver the reward for winter's patience. Peak daylight: {day_length}.",
        "The year's most generous hours are now: {day_length} of usable light.",
        "You've reached the top of the light curve: {day_length} today.",
        "Maximum brightness. {day_length} of daylight—the sun's full output.",
        "This is the peak. {day_length} of light. The slow decrease begins after the solstice.",
    ],
    
    "post_solstice_grind": [
        "The cold is real, but so is this: you've already gained {hours_gained} since the solstice. The turnaround is underway.",
        "Winter's grip feels solid, but the numbers show {hours_gained} more daylight than December's minimum.",
        "It's cold and dark, but you're {hours_gained} ahead of the solstice already. The climb has definitely begun.",
        "January asks for patience and delivers progress: {hours_gained} more light than the darkest day.",
        "The weather says winter. The daylight says recovery: +{hours_gained} since the turning point.",
        "The solstice was the bottom. You've climbed {hours_gained} since then, even if it doesn't feel dramatic yet.",
        "Winter is obvious. The returning light is subtle. But you're already {hours_gained} ahead.",
        "The grind continues, but so does the gain: {hours_gained} of progress since December.",
        "Cold and dark, but {hours_gained} richer in light than the year's minimum. That adds up.",
        "The hardest days are behind you astronomically. {hours_gained} of progress proves it.",
        "Winter feels stuck. The light is moving. {hours_gained} more than the solstice.",
        "This is the slow climb. You've made {hours_gained} of measurable progress.",
        "The solstice was the low point. You're {hours_gained} up from there.",
        "January's hidden gift: {hours_gained} more light than just weeks ago.",
        "It's a grind, but it's working. {hours_gained} gained since the lowest point.",
    ],
    
    "good_streak": [
        "Clear skies today, tomorrow, and beyond—{streak_days} days of good weather ahead. The forecast is cooperating.",
        "This is a genuine stretch of good weather. {streak_days} days of decent conditions ahead.",
        "The forecast shows {streak_days} consecutive good days. That's worth planning around.",
        "A proper run of good weather: {streak_days} days. Streaks like this deserve action.",
        "Day after day of good conditions ahead. {streak_days} days of cooperative weather.",
        "The forecast is consistent: good, good, good. {streak_days} days to work with.",
        "{streak_days} good days in sequence. That's a pattern worth using.",
        "An actual stretch of fair weather: {streak_days} days. Plan the outdoor stuff.",
        "The next {streak_days} days all look good. Make plans that need sunshine.",
        "A reliable run of decent weather. The forecast is delivering.",
        "Clear skies through the forecast. That's your runway for {streak_days} days.",
        "Good conditions stacked up ahead. {streak_days} days of opportunity.",
        "This is what a stable pattern looks like. {streak_days} good days.",
        "{streak_days} days of decent weather ahead. The forecast is being generous.",
        "A streak of good weather—{streak_days} days to do what needs doing outside.",
    ],
    
    "grey_stretch": [
        "The week looks grey throughout—{streak_days} days of clouds ahead. Time to embrace indoor activities.",
        "A stretch of overcast: {streak_days} days. The weather wants you to slow down.",
        "{streak_days} days of grey ahead. Good time for indoor projects.",
        "The forecast is consistent: clouds, clouds, clouds for {streak_days} days.",
        "An extended grey period. Books, projects, and indoor activities.",
        "The sky is taking a break from blue. {streak_days} days of grey ahead.",
        "A reliable run of overcast weather. Adjust outdoor expectations.",
        "Grey days stacked up ahead. {streak_days} days to work with indoor lighting.",
        "The clouds have set up camp for {streak_days} days. Plan accordingly.",
        "Extended grey means indoor time. {streak_days} days of it ahead.",
        "The forecast is monochromatic. {streak_days} cloudy days coming.",
        "{streak_days} days of clouds ahead. Might as well lean into it.",
        "The overcast settles in for {streak_days} days. Indoor plans are the smart move.",
        "Grey weather in bulk: {streak_days} days. A good stretch for catching up on indoor tasks.",
        "A prolonged grey stretch: {streak_days} days. The weather's way of suggesting you stay in.",
    ],
    
    "breakthrough_day": [
        "Today breaks the streak. After {bad_days} days of grey, the sun finally shows up.",
        "The waiting paid off. Today is the day the weather remembered to cooperate.",
        "After {bad_days} days of grey, today delivers. The sun is out.",
        "The clouds finally moved on. Today is the breakthrough after {bad_days} grey days.",
        "This is the day the pattern broke. Sun after {bad_days} days of overcast.",
        "The grey streak ends today. After {bad_days} days, the sun returns.",
        "After {bad_days} grey days, today stands out. The sky remembered how to be blue.",
        "The breakthrough arrived. Today is noticeably better after {bad_days} days of grey.",
        "{bad_days} days of waiting, and then this: actual sunshine. Today is the payoff.",
        "The overcast phase is over. Today marks the return of clear skies after {bad_days} days.",
        "This is what patience delivers: the sun, finally, after {bad_days} days without it.",
        "The grey gave way. Today ends a {bad_days}-day stretch of clouds.",
        "After the wait, the sun showed up. Today feels different after {bad_days} grey days.",
        "The streak of grey broke overnight. Today is the other side.",
        "Finally, a day that matches what you've been waiting for. The sun is back after {bad_days} days.",
    ],
    
    "weekend_good": [
        "The weekend forecast looks solid. Saturday and Sunday both show good conditions for outdoor plans.",
        "Good news for the weekend: clear skies on both days. Plan something outside.",
        "The forecast saved the good weather for the weekend. Saturday and Sunday both look decent.",
        "Your weekend looks workable. Outdoor plans are reasonable to make.",
        "Saturday and Sunday both look favorable. Good timing if you have outdoor activities.",
        "The weekend weather is cooperating. Both days look good.",
        "Clear weekend ahead. The forecast delivered where it counts.",
        "Good conditions for Saturday and Sunday. The week is ending well.",
        "The weekend forecast is promising. Outdoor options are open.",
        "Both weekend days look good. That's worth planning around.",
        "The week delivers where it matters: a good weekend ahead.",
        "Saturday and Sunday are both on your side weather-wise.",
        "Weekend sunshine looks likely. The forecast is favorable.",
        "The week finishes strong: good weather for the weekend.",
        "Clear skies for the weekend. Good timing for outdoor activities.",
    ],
    
    "weekend_bad": [
        "The weekend looks wet. Indoor plans might be the smarter choice.",
        "Rain on Saturday, more on Sunday. The weekend is an indoor one.",
        "The forecast suggests a cozy weekend—clouds and rain throughout.",
        "The weekend weather isn't cooperating. Time for indoor alternatives.",
        "Grey skies for Saturday and Sunday. The week ends quietly indoors.",
        "Rain moves in for the weekend. Adjust expectations accordingly.",
        "The weekend will be wet. Plan for movies, books, or cooking.",
        "Overcast both days this weekend. Indoor activities make sense.",
        "The forecast recommends staying in this weekend. Good advice.",
        "A wet weekend ahead. Sometimes that's what the weather delivers.",
        "Saturday and Sunday both look grey. Embrace indoor time.",
        "The weekend is for inside activities. The weather is making that call.",
        "Rain for both weekend days. Cozy plans are the right approach.",
        "The weekend forecast says 'stay in.' It's accurate.",
        "Grey weekend ahead. Good weather for indoor projects.",
    ],
    
    "stable_focus_light": [
        "The weather is steady and unremarkable—which puts the focus on the light: {day_length} of daylight today.",
        "Nothing dramatic in the forecast. Just the quiet progress of {delta_min} more minutes per day.",
        "Stable conditions mean the real story is the daylight: {day_length} and changing.",
        "The weather is background. The light—{day_length}—is the actual news.",
        "Uneventful skies. That leaves room to notice you have {day_length} of daylight today.",
        "The forecast is calm. The daylight isn't static—it's changing by {delta_min} minutes per day.",
        "When weather does nothing interesting, the light becomes the main story.",
        "A quiet forecast. Worth noting you have {day_length} of daylight today.",
        "The weather is being boring. The light isn't—{delta_min} more minutes today.",
        "Nothing to report weather-wise. But {day_length} of light is worth mentioning.",
        "Stable conditions. The interesting thing is the {delta_min} minutes the day is changing.",
        "The forecast is flat. The daylight curve is not—{delta_min} minutes of change.",
        "Unremarkable weather clears space for noticing {day_length} of daylight.",
        "Calm skies let you focus on what matters: {day_length} of usable light.",
        "The weather has no story today. The light does: {delta_min} minutes of daily change.",
    ],
    
    "spring_acceleration": [
        "This is the fast phase. The light is gaining {delta_min} minutes daily—the steepest climb of the year.",
        "The daylight is increasing quickly now: +{delta_min} minutes per day. You can see the evenings stretching.",
        "The acceleration is measurable. {delta_min} minutes daily means visible change week to week.",
        "This is when waiting turns to momentum. +{delta_min} minutes each day adds up fast.",
        "The daylight gains are at their maximum now: {delta_min} minutes daily.",
        "The light is moving fast: {delta_min} minutes per day. The evenings are noticeably longer.",
        "The light is gaining at its fastest rate: +{delta_min} minutes daily.",
        "This is the dramatic phase: {delta_min} minutes gained per day. Evenings expand visibly.",
        "Maximum acceleration: the light adds {delta_min} minutes daily. Real progress.",
        "The gains are steep now: +{delta_min} minutes per day. This is the fast part of the curve.",
        "You're in the acceleration zone. {delta_min} minutes daily is significant.",
        "The fastest gains of the year: {delta_min} minutes of extra light every single day.",
        "Rapid progress: +{delta_min} minutes daily.",
        "This is the steepest part of the curve: {delta_min} new minutes every 24 hours.",
        "The pace is obvious now. {delta_min} minutes per day—the sprint phase.",
    ],
    
    "solstice_approaching": [
        "The solstice is {days_to_solstice} days away. You're in the final approach to the year's turning point.",
        "Only {days_to_solstice} days until the solstice. The light is almost at its {peak_or_min}.",
        "The solstice approaches: {days_to_solstice} days. The year is about to pivot.",
        "We're in solstice territory—just {days_to_solstice} days from the astronomical milestone.",
        "{days_to_solstice} days to the solstice. The curve is about to flatten and reverse.",
        "The countdown is on: {days_to_solstice} days until the year turns.",
        "Solstice {days_to_solstice} days away. This is the final stretch toward {peak_or_min} light.",
        "Almost there: {days_to_solstice} days to the solstice. A turning point approaches.",
        "The solstice is in sight—{days_to_solstice} days. The annual rhythm is about to shift.",
        "{days_to_solstice} days until the direction changes. The solstice is nearly here.",
        "Counting down: {days_to_solstice} days to the solstice. The pivot point is close.",
        "The turning point is {days_to_solstice} days away.",
        "Nearly at the solstice: {days_to_solstice} days. The year's big milestone approaches.",
        "{days_to_solstice} days to go. The solstice will mark a new direction.",
        "The solstice countdown: {days_to_solstice} days until the annual reversal.",
    ],
}


# ===== SEASONAL PHASE DESCRIPTIONS =====
SEASONAL_PHASE = {
    "deep_winter": [
        "This is January's deal: cold outside, but the light account is already growing.",
        "Deep winter has settled in, but the solstice already happened—the days are getting longer.",
        "The coldest weeks coincide with the start of light recovery. The pattern has already reversed.",
        "January's weather doesn't match its astronomy: the harshest cold comes after the light starts returning.",
        "Winter at its coldest, but astronomically we're already past the lowest point.",
        "The season is harsh, but the light has begun its slow comeback.",
        "Deep winter feels stuck. It isn't—the climb started at the solstice.",
        "Cold and dark dominate, but the calendar has already turned.",
        "This is winter's main event. The days are lengthening behind the scenes.",
        "Winter's grip is firm while daylight quietly increases.",
        "The harshest cold arrives after the turn. The light is already ahead of the weather.",
        "January asks you to trust the process: the return of light is already happening.",
        "Deep winter is the bridge between the solstice and visible change. We're on it.",
        "The cold is intense, but so is the daily gain. Both are real.",
        "The quiet truth of this season: every day is longer than the last.",
        "January's job is endurance. The light is doing its job too.",
    ],
    "late_winter": [
        "Late winter shows real momentum now—daylight gains are accelerating noticeably.",
        "February's energy comes from knowing change is close and visible.",
        "This is the sprint phase: daylight gains accelerate toward the equinox.",
        "Late winter delivers evidence. The light proves change is coming.",
        "The frustration of late winter is justified—the change is so close.",
        "February and March are when waiting gets harder because you can see the finish line.",
        "The push toward spring is obvious now. The light is moving fast.",
        "Late winter is active waiting. Change is visible in the numbers.",
        "This is the season of almost. The light is outpacing the weather.",
        "The impatience of late winter makes sense. The end is in sight.",
        "February's restlessness is progress in disguise. The light is moving fast now.",
        "Late winter is the gap between knowing and having. Soon.",
        "The fastest light gains happen now, even as winter lingers.",
        "This is the tension between what you see and what you feel coming.",
        "Late winter tests patience because relief is so close.",
        "March is justified in its impatience: the equinox is within reach.",
    ],
    "early_spring": [
        "The equinox is behind you. Days now outlast nights—the balance has shifted.",
        "Early spring is the exhale after winter. Light wins from here.",
        "You're in the bright half of the year now. That's the astronomy.",
        "Spring's arrival is official. The light proves what the weather sometimes denies.",
        "The equinox marked the turn. You're on the generous side of the calendar now.",
        "Early spring is evidence: longer days, earlier dawns, later light.",
        "The recovery is underway. The light is abundant again.",
        "This is when the return becomes obvious. Spring has arrived.",
        "Early spring is relief made tangible. The dark half is behind you.",
        "The light half of the year has begun. You can feel the difference each evening.",
        "Spring's first chapter: days longer than nights, and getting longer still.",
        "The equinox was the threshold. You've crossed it.",
        "Early spring is the payoff for winter's patience. The light is back.",
        "This is the season of enough. Enough light, enough warmth starting.",
        "The year has tipped toward brightness. Early spring is the proof.",
        "The green is coming. Spring is writing itself across the landscape.",
    ],
    "late_spring": [
        "Late spring is the approach to peak light. The longest days are near.",
        "You're climbing toward the summit. Maximum light is weeks away.",
        "Late spring offers some of the best light conditions of the year.",
        "The climb toward summer solstice continues. Each day adds more.",
        "This is the phase where light is abundant. The peak is close.",
        "Late spring is the runway to peak daylight. Almost there.",
        "The approach to maximum light: seemingly endless evenings.",
        "Every week now brings the peak closer. The light is accumulating.",
        "Late spring is the anticipation of fullness. The longest days approach.",
        "You're in the upper part of the light curve. The summit is visible.",
        "This is the season of long evenings getting longer. Peak is near.",
        "Late spring is the final push upward. Maximum light awaits.",
        "The days are generous and getting more so. The solstice approaches.",
        "This phase is pure accumulation. More light every day.",
        "Late spring: when evenings feel endless because they nearly are.",
        "The abundance of May previews June's peak.",
    ],
    "peak_summer": [
        "You're at the top. The year offers no longer day than these.",
        "Peak summer is the summit. From here, the only way is gently down.",
        "The longest days of the year are now. This is what the climb was for.",
        "Summer solstice territory: maximum light, maximum evening.",
        "You're standing at the peak of the light cycle.",
        "This is the plateau at the top. The most light the year offers.",
        "Peak summer is arrival. You've reached the destination.",
        "The year's summit: more light than any other time.",
        "These days are the payoff for winter. Peak light.",
        "The longest days are here. The gentle descent begins after, but not yet.",
        "Peak summer is the pause at the top before the turn.",
        "Maximum daylight. The year's most generous offering.",
        "This is the apex. The light has reached its highest point.",
        "Peak summer: when sunset feels like it might never come.",
        "You're at the top. The light doesn't climb higher than this.",
        "The abundant light of midsummer. This is the maximum.",
    ],
    "late_summer": [
        "Late summer is the slow decline. Still bright, but the peak is behind you.",
        "The days are noticeably shorter than at the solstice, but still generous.",
        "Late summer is abundance with awareness. The light is receding.",
        "You're past the peak, but the descent is gentle. Summer lingers.",
        "The retreat from maximum light is underway, but slow.",
        "Late summer is the long goodbye to the longest days. Still plenty left.",
        "The light is stepping back, but there's still plenty of it.",
        "This is the descent phase, but it's the gentlest part of the curve.",
        "Late summer holds on to what it has. The evenings are still long.",
        "Past the peak, but summer's generosity extends into the decline.",
        "The longest days are behind you, but late summer is still generous.",
        "This is the mellow phase. Less than the peak, but more than enough.",
        "Late summer is the walk down from the summit. Still good conditions.",
        "The light is leaving, but slowly. Late summer takes its time.",
        "The descent has begun, but late summer makes it gradual.",
        "August's light has a particular quality: warm, rich, knowing the end is coming.",
    ],
    "early_autumn": [
        "The equinox signals the shift. Nights now outlast days.",
        "Early autumn is the mirror of early spring—steep change, opposite direction.",
        "You've crossed into the dark half of the year. The nights are winning now.",
        "The descent accelerates through autumn. Each week is noticeably shorter.",
        "Early autumn is when the loss becomes obvious. Sunset comes earlier fast.",
        "The balance has tipped. You're on the diminishing side now.",
        "Autumn's rapid changes mirror spring's—just pointing the other way.",
        "Early autumn is the slide. The light is retreating visibly.",
        "The equinox was the threshold. You've crossed into the darker half.",
        "This is the season of subtraction. Each day gives a little less.",
        "Early autumn is the steep part of the descent.",
        "The light recedes quickly now. Early autumn is direct about it.",
        "You're in the accelerating decline phase. The calendar is honest.",
        "Early autumn is adjustment. The evenings shrink; expectations shift.",
        "The dark half of the year has begun. Early autumn makes that clear.",
        "The contemplative season arrives. Autumn turns inward.",
    ],
    "late_autumn": [
        "Late autumn is the final approach to the year's minimum. The solstice is near.",
        "You're descending toward the bottom, but the turning point is in sight.",
        "Late autumn is the last stretch of darkness before the turnaround.",
        "The shortest days approach. Late autumn is the valley before the climb.",
        "November brings you close to the minimum. The solstice waits ahead.",
        "Late autumn is the final descent. The turnaround is almost here.",
        "The year's darkest days approach, but so does the reversal.",
        "Late autumn tests patience. The solstice will mark the change.",
        "You're nearly at the bottom of the light cycle. The climb begins soon.",
        "The descent flattens as you approach the solstice. The end is near.",
        "Late autumn is the quiet before the turn. The minimum approaches.",
        "The final days of decline. The solstice marks a new beginning.",
        "Late autumn is the valley floor. You're about to start climbing again.",
        "The darkest days are ahead, but the turnaround is weeks away, not months.",
        "Late autumn is the holding pattern before the reversal.",
        "The year is about to turn. Late autumn is the final waiting room.",
    ],
}


# ===== NATURE SIGNS BY MONTH AND WEATHER =====
# Concrete, specific observations - what you actually see
NATURE_SIGNS = {
    1: {
        "clear": [
            "On clear winter days, watch for robins—they're more visible now and singing from exposed perches to establish territory for spring.",
            "Look for woodpigeons gathering in flocks in bare fields. They're easier to spot without leaf cover.",
            "Clear January days reveal the structure of trees. You can see old bird nests and spot where squirrel dreys are hidden.",
            "Check south-facing banks on sunny days—snowdrops might already be pushing through if the ground isn't frozen.",
            "Winter sun at this angle creates dramatic long shadows. The light quality is actually great for photography.",
            "If you have a bird feeder, clear cold days bring the most visitors. Watch for goldfinches, blue tits, and great tits.",
            "Look for fieldfares and redwings in hedgerows—these winter thrushes arrived from Scandinavia and are here for the berries.",
            "Fox tracks in frost are common now. They're more active in daylight during cold spells.",
            "On clear nights, Orion is perfectly positioned in the southern sky. The winter constellations are at their best.",
            "Check for catkins on hazel bushes. They're already formed and waiting for warmer days to extend.",
        ],
        "grey": [
            "Grey January days are when you notice birds most—robins, blackbirds, and thrushes stand out against the muted backdrop.",
            "Look for bark beetles' galleries on fallen logs. Winter is a good time to examine tree bark patterns.",
            "Grey skies make lichens and mosses more visible. They're actually quite colorful when you look closely.",
            "Overcast days are good for spotting birds of prey. They hunt more actively without bright sun making them visible.",
            "Check under rotting logs for woodlice, centipedes, and beetle larvae. The invertebrate world doesn't stop in winter.",
            "Grey days reveal the evergreens: holly, ivy, and yew stand out when deciduous trees are bare.",
            "Watch for grey squirrels—they don't hibernate and are busy retrieving cached nuts now.",
            "Overcast conditions are actually ideal for examining tree bark. Lichen and fungi patterns are clearer.",
            "Listen for nuthatches—their calls carry well on quiet grey days.",
            "Check bird tables—grey days bring out the hungry visitors looking for easy food.",
        ],
        "rain": [
            "Winter rain brings slugs out. If you have a garden, they're active and feeding on any remaining vegetation.",
            "After rain, look for animal tracks in mud—fox, badger, deer, and squirrel prints are all readable now.",
            "Rain washes berries off bushes, which concentrates birds in areas where fruit remains. Watch hedgerows.",
            "Earthworms surface after rain. That's why blackbirds and thrushes are often seen on lawns in wet weather.",
            "Check for the distinctive smell of rain on cold ground—petrichor works in winter too.",
            "Rain on bare branches creates a particular dripping pattern. Each tree species sounds different.",
            "Wet bark shows different colors than dry. Oak bark goes almost black; birch stays silver.",
            "Puddles form in the same places every time. Watch which birds use them for drinking and bathing.",
            "After rain, fungi can pop up quickly. Winter brackets on dead wood are worth looking for.",
            "Wet leaf litter compresses, making it easier to spot small mammals moving underneath.",
        ],
        "snow": [
            "Fresh snow is a tracking medium. Look for rabbit, fox, and bird tracks—the story of last night's activity.",
            "Snow reveals where birds roost. Look for the patterns of droppings and melted patches under evergreens.",
            "Blackbirds flick snow aside to find invertebrates. Watch them using their feet and beaks to clear ground.",
            "Holly berries against snow is the classic winter image—and actually happens. Worth photographing.",
            "Snow shows you where wildlife paths are. Fence gaps, hedge bottoms, and field edges show regular traffic.",
            "Birds puff up their feathers in snow to trap insulating air. They look almost spherical.",
            "Check for snow fleas—tiny springtails that appear as dark specks on snow surfaces on warmer days.",
            "Deer tracks in snow are distinctive: two pointed toes, often in a straight line.",
            "Snow reveals the branching patterns of trees perfectly. Each species has a characteristic silhouette.",
            "Watch for kestrels hovering over snow-covered fields. Prey is harder to hide and easier to spot.",
        ],
        "general": [
            "This is the month when days are finally getting longer, even if the weather doesn't show it yet.",
            "January's cold often peaks this month, even though we're past the solstice. The lag is normal.",
            "Bird song increases through January. Listen for great tits starting their 'teacher-teacher' calls.",
            "If you spot snowdrops, they're often the first flowers of the year. Check sheltered spots and old gardens.",
            "Hazel catkins are worth watching. When they lengthen and turn yellow, spring is loading.",
            "Foxes are mating now. That's what the strange screaming sounds at night are.",
            "January is when tawny owls call most actively. Listen after dark for the classic 'twit-twoo' exchange.",
            "Check for frogspawn from mid-January in mild years. Some frogs spawn surprisingly early.",
            "The smell of cold air is distinctive—fewer airborne particles and lower humidity.",
            "Days are now gaining light at an accelerating rate. By month's end, it's noticeably lighter longer.",
        ],
    },
    2: {
        "clear": [
            "Snowdrops are fully out now. They're the reliable first flower—check churchyards and old gardens.",
            "On sunny February days, watch for bumblebee queens. They emerge early to search for nest sites.",
            "Crocuses are pushing through. Purple, yellow, and white varieties all open on sunny days.",
            "Birdsong intensifies in February. Great tits, song thrushes, and robins are all getting louder.",
            "Look for hazel catkins releasing pollen on clear days. The yellow dust is visible in sunlight.",
            "Early butterflies—mainly brimstones and peacocks—can appear on warm, sunny days.",
            "Sunny spots in gardens show the first growth: chives, mint, and perennial herbs are greening up.",
            "Look for frog and toad activity in ponds on warmer days. Spawning can start now.",
            "The angle of sunlight is noticeably higher than January. Shadows are shorter, light is stronger.",
            "Alder catkins open now, adding to the pollen. If you have allergies, this is when it starts.",
        ],
        "grey": [
            "Grey February reveals buds swelling on trees. Willows and cherries are especially noticeable.",
            "Overcast days are good for checking ponds. Frogs gather before spawning and are easier to spot.",
            "Listen for chiffchaffs—some overwinter and sing on mild grey days before spring migrants arrive.",
            "Grey skies don't stop snowdrops. They bloom regardless of light levels.",
            "Watch for grey herons standing motionless by water. They're easier to spot on grey days.",
            "February grey is often damp grey. Mosses and lichens are at their most colorful now.",
            "Check for early nesting activity—rooks repair nests in rookeries even on grey days.",
            "Overcast conditions suit some wildlife photography. Even lighting, no harsh shadows.",
            "Listen for drumming woodpeckers. February is when great spotted woodpeckers start advertising territory.",
            "Grey days bring out the colors in bark. Silver birch, copper beech, and red dogwood stems all show well.",
        ],
        "rain": [
            "February rain is life for the soil. Underneath, earthworms are active and roots are waking up.",
            "After rain, check for fungal brackets on dead wood. Wet conditions bring out new growth.",
            "Puddles in fields attract lapwings and other waders passing through on spring migration.",
            "Rain brings slugs and snails out. Song thrushes know this—watch for them hunting on wet lawns.",
            "Wet bark shows the texture of trees. Ash bark is rough, beech smooth, oak deeply fissured.",
            "February rain feeds the spring bulbs. Daffodils are pushing up, roots drinking deep.",
            "Check for newts in ponds after rain. They're returning to water for breeding season.",
            "Rain washes air clean. The smell after February rain is different from other months—more earthy.",
            "Wet conditions are good for transplanting. Gardeners take advantage of moist soil.",
            "After rain, look for the first celandines—glossy yellow flowers that open in damp conditions.",
        ],
        "snow": [
            "February snow on crocus flowers is the classic seasonal tension image. Spring and winter arguing.",
            "Late snow can't stop what's started. The bulbs know the light levels, not the temperature.",
            "Snow in February highlights early-nesting birds. Rooks and grey herons are already on nests.",
            "Check for animal tracks in late snow—activity has increased as breeding season approaches.",
            "February snow is often wet snow, heavy and melting. It doesn't last like January's.",
            "Snowdrops push through snow—that's what they're named for. Watch for the green tips.",
            "Late snow reveals how many birds visit your garden. Concentrated tracks around feeders.",
            "February snow compacts differently. It often has a crust from daytime melting.",
            "Watch for blackbirds flicking snow aside. They're determined feeders.",
            "Snow on early blossom—on willows, for instance—creates interesting contrasts.",
        ],
        "general": [
            "February is the acceleration month. Daylight gains are rapid now.",
            "The dawn chorus is building. By month's end, mornings sound different from January.",
            "Frogs spawn mid-February to early March typically. Check ponds for jelly-like masses.",
            "Trees are visibly preparing. Buds are swelling on everything from maples to magnolias.",
            "This is hedge-sparrow (dunnock) prime time. They sing from exposed perches now.",
            "Lesser celandines appear on banks and verges. Star-shaped yellow flowers close on cloudy days.",
            "Days are noticeably longer now. The change from January is measurable and visible.",
            "First butterflies of the year can emerge: peacocks, small tortoiseshells, brimstones from hibernation.",
            "February feels like waiting, but the activity underneath is intense. Life is loading.",
            "Birch trees show the first purple haze of buds preparing to open. The branches look softer.",
        ],
    },
    3: {
        "clear": [
            "Daffodils are out now—wild ones in woods, cultivated ones everywhere else. The yellow signals spring.",
            "On clear March days, bumblebees are everywhere. Queens are foraging to fuel new colonies.",
            "The dawn chorus is significant now. Blackbirds, song thrushes, and robins all sing before sunrise.",
            "Look for comma butterflies on sunny banks. Their ragged wing edges are distinctive.",
            "Blackthorn blossom appears on bare branches—white flowers before leaves. Very visible on sunny days.",
            "Clear March weather brings out adders from hibernation. They bask on south-facing banks.",
            "Chiffchaffs are back from Africa. Listen for their repetitive two-note song: 'chiff-chaff, chiff-chaff.'",
            "Marsh marigolds flower in wet areas now. Bright yellow, cup-shaped, and unmistakable.",
            "Wild garlic (ramsons) starts to appear in woodlands. You smell it before you see it.",
            "Tadpoles are visible in ponds now—the spawn has hatched and they're growing fast.",
        ],
        "grey": [
            "Grey March days don't stop the growth. Grass greens up, leaves emerge, life accelerates.",
            "Overcast conditions suit frog and toad activity. They're less visible to predators.",
            "Look for primroses on banks and woodland edges. They bloom pale yellow under grey skies.",
            "Grey days in March still have good birdsong. The singers don't care about cloud cover.",
            "Catkins release pollen even on grey days. The trees are on a schedule.",
            "Watch for siskins in alders. These small finches hang acrobatically to reach catkins.",
            "Grey weather brings out the smell of spring growth. The air changes even without sun.",
            "Violets flower in shade and cloud. Check along paths and under hedges.",
            "Grey March days are good for seeing deer. They feed more openly without harsh shadows.",
            "Overcast skies make it easier to spot nesting activity. Watch for birds carrying materials.",
        ],
        "rain": [
            "March rain is growth rain. Every drop feeds what's about to explode into leaf and flower.",
            "After rain, check for orange peel fungus—bright orange, cup-shaped, appearing on disturbed ground.",
            "Wet March days bring the smell of growth. The combination of rain and warming soil is distinctive.",
            "Rain on daffodils—they handle it well. The flowers nod but don't break.",
            "Wet weather keeps migrant birds grounded. Check gardens and parks for unusual visitors.",
            "March rain fills ponds for breeding amphibians. The water levels matter for their success.",
            "After rain, earthworms are on paths. That's why thrushes patrol concrete and paving.",
            "Wet March soil is perfect for digging. Gardeners and wildlife both take advantage.",
            "Rain on new leaves creates the soundtrack of spring. Each species sounds different.",
            "Check for wild garlic after rain—the scent intensifies in damp air.",
        ],
        "snow": [
            "March snow on daffodils is the classic image of seasons in conflict. Spring wins eventually.",
            "Late snow can't stop migration. Birds that started the journey are committed.",
            "Snow in March is usually short-lived. Ground temperatures are too high for it to stick long.",
            "Watch for confused bees. They emerged in warmth and now wait out the cold.",
            "March snow on green growth is particularly striking. The contrast is stark.",
            "Late snow stress-tests early flowers. Most handle it—they evolved for this.",
            "Snow at this point is a delay, not a defeat. The season has momentum.",
            "Check for early lambs in snowy fields. Breeding schedules don't wait for weather.",
            "March snow brings unusual visitors to feeders. Migrants caught out by cold.",
            "The birdsong continues through March snow. The calendar matters more than the weather.",
        ],
        "general": [
            "March is the month of visible acceleration. Everything happens at once now.",
            "The equinox means days longer than nights from here on. The dark half is over.",
            "Nesting is underway for many species. Robins, blackbirds, and thrushes are sitting on eggs.",
            "Wild daffodils in woods are worth finding. They're smaller and more delicate than garden varieties.",
            "Hedgehogs are emerging from hibernation. Watch for them on mild evenings.",
            "Tree buds are visibly swelling. Horse chestnuts are the most dramatic—sticky and large.",
            "Bumble bee queens are everywhere. Each one represents a potential colony of hundreds.",
            "March feels like the turn. Winter's grip loosens day by day.",
            "First butterflies from chrysalises (not hibernation) appear: orange tips, holly blues.",
            "The smell of the season changes. Spring has a particular scent—growth, pollen, wet earth.",
        ],
    },
    4: {
        "clear": [
            "April sun on cherry blossom is one of the best sights of the year. The trees are at their peak now.",
            "The dawn chorus is intense now. Get up early—the singing starts before 5 AM.",
            "Swallows are back from Africa. Look for them hawking insects over water and fields.",
            "Orange-tip butterflies are a spring specialty. Males are unmistakable with orange wingtips.",
            "Bluebells are opening in woods. The carpet of blue under trees is worth seeking out.",
            "Cuckoos call from mid-April. The distinctive two-note sound carries far on clear days.",
            "House martins return and start building mud nests under eaves. Watch for their white rumps in flight.",
            "Apple blossom opens on warm April days. The combination of pink and white is classic.",
            "Adders are fully active now, basking on sunny banks. Give them space—they want to avoid you too.",
            "Tadpoles are growing legs. Check ponds to see the transformation in progress.",
        ],
        "grey": [
            "Grey April days don't slow the growth. Everything is in overdrive regardless of sun.",
            "Overcast skies are perfect for bluebell photography. The colors are truer without harsh light.",
            "Listen for willow warblers on grey days. Their descending song is everywhere now.",
            "Grey conditions suit nightingales if you're lucky enough to have them nearby. They sing day and night.",
            "Overcast April is still building season. Birds don't stop nesting for clouds.",
            "Grey days highlight the fresh green of new leaves. The color is vivid against grey sky.",
            "Listen for the first swifts. Their screaming calls are easier to hear when you're not distracted by sun.",
            "Grey April brings out the woodland flowers. Wood anemones carpet forest floors.",
            "Overcast conditions make it easier to spot nesting activity. Watch for birds carrying materials.",
            "Check ponds on grey days—great crested newts display underwater, less visible in bright sun.",
        ],
        "rain": [
            "April showers feed May flowers—the saying exists for a reason. This rain is productive.",
            "Rain on new leaves creates the best sound of spring. Each tree species has a different tone.",
            "Wet April days see intense slug and snail activity. Thrushes know and hunt accordingly.",
            "Check for frogs still in ponds after rain. Some arrive late for spawning.",
            "April rain makes grass grow visibly fast. Lawns need mowing weekly now.",
            "Wet weather suits ground-nesting birds. The soft soil is easier to probe for invertebrates.",
            "After rain, watch for earthworms on paths. Birds patrol these hard surfaces for easy meals.",
            "April rain on blossom—the petals scatter, making a pink and white carpet beneath trees.",
            "Wet days bring out the green. The color saturation of April after rain is remarkable.",
            "Rain fills bird baths and natural puddles. Watch for bathing activity after showers pass.",
        ],
        "snow": [
            "April snow is rare but not unknown. It's weather's way of reminding you winter isn't quite done.",
            "Late snow on blossom creates surreal images. Worth photographing if it happens.",
            "April snow can't stop what's already flying. Swallows and martins cope—they evolved for variable weather.",
            "Snow at this point is a brief interruption. Ground temperatures don't support it lasting.",
            "Watch for confused insects. Bees that were foraging retreat to shelter.",
            "April snow on bluebells is particularly striking—blue and white together.",
            "Nesting birds sit tight through April snow. The eggs need constant warmth.",
            "Late snow stress-tests migrant birds. They've come thousands of miles and can't turn back.",
            "April snow melts fast. The high sun angle works against it even when temperatures drop.",
            "The green growth shows through melting April snow. Spring is too strong to stop now.",
        ],
        "general": [
            "April is peak nesting season. Move carefully in undergrowth—ground-nesting birds are everywhere.",
            "The dawn chorus peaks now. The volume and variety won't be matched at any other time.",
            "Bluebells have a short season. If you want to see them at their best, April is the month.",
            "Swifts arrive late April, screaming through evening skies. They've flown from Africa.",
            "Tree leaves are emerging fast. The canopy closes week by week.",
            "Butterflies are everywhere now: orange tips, peacocks, small whites, brimstones.",
            "The smell of blossom is pervasive. Apple, cherry, hawthorn—April is fragrant.",
            "Bird song reaches its annual peak. Every species is advertising territory.",
            "Dandelions flower abundantly. They're important for pollinators, not just weeds.",
            "The warmth is becoming reliable now. April evenings are mild enough for outdoor activity.",
        ],
    },
    5: {
        "clear": [
            "May warmth brings butterflies in clouds. Painted ladies, commas, and whites are everywhere.",
            "Hawthorn blossom (may blossom) fills hedgerows with white and a distinctive sweet scent.",
            "Swifts are fully present now, screaming through evening skies in feeding parties.",
            "Cow parsley lines every road and lane. The white umbel flowers are the backdrop of May.",
            "Baby birds are fledging. Watch for clumsy juveniles in gardens—they're learning to fly.",
            "Elderflowers open on warm May days. If you're making cordial, this is the harvest window.",
            "Clear May evenings are long and warm. Sunset comes after 9 PM now.",
            "Orchids flower in meadows and on chalk downland. Bee orchids, pyramidal orchids—worth seeking.",
            "Mayflies emerge in clouds near water. They're the defining insect of the month.",
            "Horse chestnut candles are at their peak—tall white or pink flower spikes on every tree.",
        ],
        "grey": [
            "Grey May is still warm May. The heat doesn't depend on sun.",
            "Overcast days are good for finding fledglings. They hide in vegetation and call for food.",
            "Grey skies bring out the vivid green of May. The leaves are fresh and saturated.",
            "Listen for cuckoos on grey days. Their call carries well without visual distractions.",
            "Grey May days are good for wildlife photography. Even lighting, no harsh shadows.",
            "Cow parsley glows white against grey skies. The contrast is striking.",
            "Overcast conditions suit slow worms. They emerge from hiding more readily.",
            "Grey doesn't stop the elderflowers. They're still harvestable.",
            "Listen for whitethroats in hedgerows—their scratchy song is characteristic of May.",
            "Grey May days still have long evenings. The light lasts even without direct sun.",
        ],
        "rain": [
            "May rain makes gardens grow almost visibly. You can practically watch things get taller.",
            "After rain, the air smells of growth—cut grass, wet earth, and flowers combined.",
            "Wet May days suit snails. You'll see the large garden snails on walls and plants.",
            "Rain on elderflowers—pick them after they dry, or the cordial will be watery.",
            "Slugs are active in wet May conditions. Thrushes appreciate the easy hunting.",
            "May rain is usually warm rain. It doesn't have January's chill.",
            "After showers, check for rainbow opportunities. The combination of sun and moisture creates them.",
            "Wet conditions suit grass growth. Meadows become knee-high quickly.",
            "Rain-soaked blossom is heavy. Some branches bend under the water weight.",
            "The smell of rain on may blossom is distinctive—sweet and slightly musty.",
        ],
        "snow": [
            "May snow is extremely rare and extremely temporary. It makes headlines when it happens.",
            "Snow in May can't survive contact with warm ground. It melts on impact.",
            "If it snows in May, the leaves and flowers prove how absurd it is.",
            "May snow is weather's anomaly. Everything green contradicts it.",
            "Any May snow would melt in hours. The season is far too advanced.",
        ],
        "general": [
            "May is the month of abundance. Everything is growing, flowering, or nesting.",
            "The canopy is nearly closed now. Woodland floor plants finish flowering as shade increases.",
            "Baby birds are everywhere. Fledgling season runs through the month.",
            "Hay fever peaks for many as grass pollen levels rise. Check the forecast if you're affected.",
            "May evenings are the first genuinely summer-like ones. Sitting outside is comfortable.",
            "The dawn chorus continues but thins slightly. Some birds have stopped singing and started nesting.",
            "Butterflies are at their spring peak. Take time to watch and identify them.",
            "Wild garlic finishes flowering but the leaves are still pungent. Foraging season continues.",
            "The landscape is fully green now. The transition from bare to leafy is complete.",
            "May brings the sense that summer is actually here, not just coming.",
        ],
    },
    6: {
        "clear": [
            "The summer solstice approaches—these are nearly the longest days of the year.",
            "Elderflowers are at peak harvest now. The flat white flower heads are ready for cordial.",
            "Roses are in full bloom. The scent is everywhere on warm June evenings.",
            "June evenings are the longest. Sunset after 9:30 PM gives hours of usable light.",
            "Dog roses bloom pink and white in hedgerows. The simple five-petaled flowers are abundant.",
            "Orchids flower on chalk grassland. This is the peak month for many species.",
            "Honeysuckle scents the evening air. The fragrance intensifies at dusk for night-flying pollinators.",
            "Meadow grasses flower. If you have hay fever, this is peak pollen season.",
            "Swifts are everywhere, screaming through evening skies. They're feeding hard for breeding.",
            "First summer fruits ripen: strawberries, gooseberries, early raspberries in gardens.",
        ],
        "grey": [
            "Grey June is still long June. The light lasts until after 10 PM regardless of cloud.",
            "Overcast summer days are cooler and easier for physical activity. Less heat stress.",
            "Grey conditions don't affect fruit development. Strawberries ripen by calendar, not by sunlight.",
            "June grey is brighter than winter sun. The background light level is still high.",
            "Overcast days suit outdoor work. Less glare, less sunburn risk.",
            "Grey June is good for photography. The soft light flatters flower colors.",
            "Listen for summer bird calls—cuckoos, swifts, warblers—on grey days.",
            "Grey doesn't stop the elderflowers. They're still harvestable.",
            "Overcast June evenings are long and mild. Good for outdoor eating.",
            "The green of June is intense even under grey skies. The color saturates everything.",
        ],
        "rain": [
            "June rain feeds the garden abundance. Everything drinks and grows.",
            "Wet summer days bring out slugs in numbers. Gardens need attention.",
            "After rain, the air smells of roses and wet grass. June's signature scent.",
            "Rain on roses—they handle it well. The blooms may nod but rarely damage.",
            "June showers are usually warm. The rain is different from spring rain.",
            "Wet conditions suit strawberry growth, though pick them dry or they rot.",
            "After June rain, mushrooms can appear in lawns. The fungi respond quickly.",
            "Rain can't shorten June days. The light lasts whatever the weather.",
            "Wet June evenings are still long evenings. The sky stays light until late.",
            "The smell of rain on warm ground is strongest in summer. June delivers it.",
        ],
        "snow": [
            "June snow doesn't happen at these latitudes. The season has moved far beyond it.",
            "Snow is not a June concept. Look at the garden—it's full summer.",
            "If someone told you it snowed in June, check their location—maybe high altitude.",
        ],
        "general": [
            "June is the month of maximum light. Use it—this is the peak of available daylight.",
            "The summer solstice marks the turn. After it, days shorten, but gradually.",
            "Evenings are the real gift of June. Hours of usable light after work.",
            "Baby birds are fledging in waves. Many species have second broods underway.",
            "Wild strawberries ripen in sunny spots. They're small but intensely flavored.",
            "Hay meadows are ready for first cut. The grass is tall and heavy with seed.",
            "The dawn chorus has quietened. Many birds are busy feeding young, not singing.",
            "June is when 'summer' actually feels real. Consistent warmth, long light.",
            "Butterflies are abundant: meadow browns, ringlets, skippers in grassland.",
            "The year's peak light deserves attention. Notice how late the twilight lasts.",
        ],
    },
    7: {
        "clear": [
            "Lavender and buddleia are butterfly magnets. Watch for peacocks, red admirals, and painted ladies.",
            "Wild blackberries start ripening mid-July. The first ones appear in sunny spots.",
            "Swifts begin leaving for Africa late July. Their screaming flights won't last much longer.",
            "Clear July evenings are warm enough to sit out until 10 PM. The light lasts.",
            "Heather starts blooming on moorland. The purple spreads through August.",
            "Cornfields turn gold as grain ripens. The harvest approaches.",
            "Crickets and grasshoppers provide the July soundtrack. Listen for them in long grass.",
            "July sun dries the ground hard. Paths and lawns show the lack of rain.",
            "Red admiral butterflies are common now. They migrate here from continental Europe.",
            "Evening light in July has a golden quality. The sun angle has shifted from June.",
        ],
        "grey": [
            "Grey July is still warm July. The heat doesn't depend on direct sun.",
            "Overcast summer days suit outdoor activity. Less brutal than blazing sun.",
            "Grey doesn't stop blackberries ripening. Check hedgerows anyway.",
            "Cloudy July reduces water evaporation. Gardens appreciate the break.",
            "Grey days are good for walks. Less sunburn and heat exhaustion risk.",
            "Listen for grasshoppers on grey days. They're active in warmth, not light.",
            "Overcast July has long twilights. The evenings stay light until very late.",
            "Grey is easier on the eyes. Flowers and greenery show their colors well.",
            "The buzzing continues on grey days. Bees and hoverflies don't stop for clouds.",
            "Grey July is good for garden work. Cooler, no glare, plants don't wilt as fast.",
        ],
        "rain": [
            "July rain after dry weeks brings relief. Gardens and wildlife appreciate it.",
            "After summer rain, mushrooms appear in lawns and woods. The response is quick.",
            "Wet July days smell like summer rain—warm, earthy, and green.",
            "Rain on ripe berries can cause them to split. Pick before if possible.",
            "July showers are often brief and warm. Classic summer afternoon rain.",
            "After rain, the bird bath gets competition from puddles. Watch for bathing.",
            "Wet conditions bring out the smell of decay. Autumn is loading.",
            "Rain in August feels like a threshold. Summer is winding down.",
            "Wet blackberries are harder to pick but still worth it.",
            "Late summer rain creates fog in valleys. The transition weather begins.",
        ],
        "snow": [
            "July snow is not a thing. The concept doesn't apply.",
            "Snow in July would require being on a high mountain or in the wrong hemisphere.",
        ],
        "general": [
            "July is the month when you feel summer has actually arrived. The heat is real.",
            "The days are shortening, but imperceptibly. You won't notice yet.",
            "Swifts leave late July. Watch for their departure—they won't return until May.",
            "Blackberries are the main foraging opportunity now. Free fruit in every hedgerow.",
            "July is butterfly month. Species diversity peaks.",
            "The harvest begins. Early grain crops are cut in good weather.",
            "Gardens need watering. July can be dry and demanding.",
            "Crickets and grasshoppers make July sound like summer.",
            "The light is still generous, even as it shortens. Evenings stretch late.",
            "July warmth lingers into evening. Sitting outside is comfortable until dark.",
        ],
    },
    8: {
        "clear": [
            "Blackberries are fully ripe now. The picking season is at its peak.",
            "Clear August days have a golden quality. The light is aging toward autumn.",
            "Harvest is in full swing. Combine harvesters work the grain fields.",
            "The Perseid meteor shower peaks mid-August. Watch for shooting stars after midnight.",
            "Apples and pears are ripening. Early varieties are ready to pick.",
            "Swallows and martins gather on wires. They're preparing for the journey south.",
            "Fields of stubble replace tall grain. The landscape changes fast after harvest.",
            "August sun is warm but lower than July. The angle has shifted noticeably.",
            "Wasps are at their annual peak. They're looking for sugar now, not protein.",
            "Evening light in August is particularly golden. The quality is different from June.",
        ],
        "grey": [
            "Grey August still ripens fruit. The blackberries don't need sun to sweeten.",
            "Overcast late summer has a contemplative quality. The year is turning.",
            "Grey doesn't stop the harvest. Farmers work through if rain holds off.",
            "Cloudy August days are good for picking fruit. Less heat stress.",
            "Grey days in August feel transitional. Something is shifting.",
            "Listen for robin song returning. They've been quiet since nesting; now they sing again.",
            "Overcast August is good for walking. Less brutal heat.",
            "Grey doesn't affect the wasps. They're still sugar-hunting.",
            "The greenery is getting tired. August grey shows the wear of the season.",
            "Cloudy days make mushroom hunting easier. Less contrast, fewer shadows.",
        ],
        "rain": [
            "August rain after dry weeks is welcome. Gardens and farms appreciate it.",
            "Late summer showers bring mushrooms. The fruiting season begins.",
            "Wet August days smell like ripeness and earth. The combination is distinctive.",
            "Rain on grain fields is bad news for farmers. Timing matters at harvest.",
            "August rain refreshes tired vegetation. The garden gets a second wind.",
            "After rain, check for field mushrooms in pastures. They appear quickly.",
            "Wet conditions bring out the smell of decay. Autumn is loading.",
            "Rain in August feels like a threshold. Summer is winding down.",
            "Wet blackberries are harder to pick but still worth it.",
            "Late summer rain creates fog in valleys. The transition weather begins.",
        ],
        "snow": [
            "August snow would be news. It doesn't happen in normal conditions.",
            "Snow in August is for mountain peaks, not lowlands.",
        ],
        "general": [
            "August is the harvest month. The work of the year comes to fruition.",
            "Days are noticeably shorter than July. The change is measurable now.",
            "Blackberries are the main foraging event. Hedgerows are loaded.",
            "Swallows gather for migration. Their departure is coming soon.",
            "Gardens look tired. The growing season is past its peak.",
            "Wild fruits ripen: elderberries, sloes, hawthorn berries.",
            "The birdsong has mostly stopped. Only robins sing regularly now.",
            "August has a melancholy edge. The abundance is real, but temporary.",
            "Nights are cooling. The contrast with daytime warmth is sharper.",
            "The light is changing. August evenings are noticeably shorter than June.",
        ],
    },
    9: {
        "clear": [
            "September sun on turning leaves is the start of the color show.",
            "Clear September days are harvest days. Apples, pears, plums are ready.",
            "Spider webs catch morning dew, revealed by low autumn sun. They're everywhere now.",
            "Swallows gather in numbers before departure. Watch for massed flocks on wires.",
            "Mushrooms fruit in woods after rain. Field mushrooms appear in pastures.",
            "Elderberries are ripe—purple-black clusters ready for wine or jelly.",
            "Clear September days have a particular clarity. The air changes quality.",
            "Migrating birds pass through—warblers, flycatchers, chats heading south.",
            "Blackberries are past their best now but still harvestable.",
            "The equinox approaches. Day and night balance, then tip toward dark.",
        ],
        "grey": [
            "Grey September accelerates the mood shift. Autumn is arriving.",
            "Overcast days suit mushroom hunting. The fungi don't need sun.",
            "Grey skies make autumn colors more saturated. The leaves glow against cloud.",
            "Cloudy September matches the contemplative season.",
            "Grey doesn't stop the harvest. Farmers work through.",
            "Overcast conditions suit spider web photography. Even lighting reveals structure.",
            "Grey September mornings are often misty. The dew point drops as nights cool.",
            "Listen for tawny owls starting up again. Their autumn calling begins.",
            "Grey skies bring the smell of autumn—damp leaves, mushrooms, cooler air.",
            "Overcast September is good for walking. Less harsh light, comfortable temperature.",
        ],
        "rain": [
            "September rain brings mushrooms in abundance. The fruiting is triggered.",
            "Autumn showers strip the first leaves. The process is starting.",
            "Wet September accelerates decomposition. The smell of autumn strengthens.",
            "Rain on fallen leaves creates the quintessential autumn sound.",
            "After September rain, check for fungi. The wet conditions trigger fruiting.",
            "Wet days suit earthworms. They surface after rain; birds take advantage.",
            "September rain is cooler than summer rain. The temperature has shifted.",
            "The smell of wet September is distinctive—leaf mold, earth, fungi.",
            "Rain feeds the last fruits: apples swell, sloes ripen.",
            "Wet conditions make some harvesting difficult. Timing matters.",
        ],
        "snow": [
            "September snow is unlikely but not impossible at altitude.",
            "Snow this early would be notable. The trees are still in leaf.",
            "If September snow happens, it's a sign of unusual cold.",
        ],
        "general": [
            "September is the transition month. Summer ends, autumn begins.",
            "The equinox means nights now exceed days. The dark half starts.",
            "Mushroom season peaks. Knowledge matters—some are edible, some dangerous.",
            "Swallows leave through September. By month's end, they're mostly gone.",
            "Harvest festivals mark the season. The agricultural year reaches completion.",
            "Spider webs are everywhere. The orb weavers are at their largest.",
            "The smell of autumn is in the air—decomposing leaves, damp earth.",
            "Days shorten rapidly now. The rate of change matches spring in reverse.",
            "Migrant birds pass through. Gardens may hold unusual visitors.",
            "The color change begins. Early turners include rowans, cherries, acers.",
        ],
    },
    10: {
        "clear": [
            "October sun on peak autumn color is one of the year's great sights.",
            "Clear October days are cold but beautiful. The light is precious.",
            "Low autumn sun through colored leaves creates stained glass effects.",
            "Migrating redwings and fieldfares arrive from Scandinavia. Listen for their calls.",
            "Clear October nights bring the first hard frosts. Gardens need protection.",
            "The best autumn color needs clear skies. Enjoy it when it coincides.",
            "Fungi are everywhere in woods—brackets, puffballs, and more.",
            "October clarity means cold nights and warm days. The contrast is sharp.",
            "Starling murmurations build through the month. Watch for them at dusk.",
            "Clear evenings reveal autumn constellations. The Pleiades are rising.",
        ],
        "grey": [
            "Grey October makes colored leaves glow brighter. The contrast works.",
            "Overcast days suit photography. Even light, no harsh shadows on foliage.",
            "Cloudy October accelerates leaf fall. Wind and rain strip the trees.",
            "Grey matches the contemplative mood. The season turns inward.",
            "Overcast conditions suit mushroom hunting. Less contrast, easier spotting.",
            "Grey October is traditional. It's what the month often delivers.",
            "Listen for redwings calling on grey days. They arrived from the north.",
            "Grey skies, colored leaves—the combination is classic October.",
            "Overcast days bring out the orange and red more vividly.",
            "Grey October is good for walking. No harsh light, comfortable temperature.",
        ],
        "rain": [
            "October rain strips leaves rapidly. The skeleton trees emerge.",
            "Wet October has its own beauty—glistening bark, wet leaves, misty air.",
            "Rain on fallen leaves creates the quintessential autumn sound.",
            "The smell of wet October: decay, earth, mushrooms.",
            "After rain, check for fungi. The wet conditions trigger fruiting.",
            "Wet days accelerate the transition. The season moves faster.",
            "October rain is cold rain. The warmth is definitely gone.",
            "Puddles of colored leaves collect in gutters and paths.",
            "Rain drives the last swallows south. Any remaining must leave now.",
            "Wet conditions suit earthworms. Blackbirds probe sodden lawns.",
        ],
        "snow": [
            "October snow is possible now. The season is tipping toward winter.",
            "Early snow on colored leaves creates dramatic photographs.",
            "Snow this month would be early but not unprecedented.",
            "October cold arrives in waves. Snow is a possibility.",
            "First snow of the season, if it comes, often falls this month.",
        ],
        "general": [
            "October is the main month for autumn color. Peak varies by species and location.",
            "Clocks change at month's end—evenings suddenly darker.",
            "Migrant birds arrive from the north: redwings, fieldfares, winter thrushes.",
            "Fungi diversity peaks. Woods are full of bracket fungi, toadstools, puffballs.",
            "Hedgehogs are fattening for hibernation. Help them with food and leaf piles.",
            "The smell of bonfires and leaf smoke marks the season.",
            "Days shorten rapidly. The change is visible week to week.",
            "Halloween marks the old Celtic new year—the crossing into darkness.",
            "Squirrels cache nuts intensively. Watch them bury and retrieve.",
            "The last butterflies—red admirals mainly—are still about on warm days.",
        ],
    },
    11: {
        "clear": [
            "November sun is precious. The bare trees don't block it, at least.",
            "Clear November days are cold but bright. The light is rationed.",
            "Low sun through bare branches creates intricate shadow patterns.",
            "Starling murmurations peak now. Watch for the evening displays.",
            "Clear November nights are frosty. Hard frost is routine now.",
            "The low sun angle is dramatic. Long shadows all day.",
            "Clear days reveal the structure of trees. Identification is easier without leaves.",
            "November frost on spider webs creates crystal structures.",
            "Clear cold mornings show your breath. Winter is definitely here.",
            "The last autumn colors persist in sheltered spots on clear days.",
        ],
        "grey": [
            "Grey November is the archetype. This is what the month often delivers.",
            "Overcast conditions suit the contemplative mood. The year is winding down.",
            "Grey skies, bare trees—November in its essential form.",
            "Cloudy November brings early darkness. The evenings close in fast.",
            "Grey doesn't stop starling murmurations. They perform regardless.",
            "Overcast November makes indoor lighting essential earlier.",
            "The grey matches the bare landscape. A kind of honesty.",
            "Grey November is traditional. Fighting it is pointless.",
            "Listen for tawny owls in the grey evenings. They call more now.",
            "Grey days make the evergreens stand out—holly, ivy, conifers.",
        ],
        "rain": [
            "November rain is cold rain. The season has shifted definitively.",
            "Wet late autumn strips the last holdout leaves. Trees are bare now.",
            "Rain on bare branches sounds different. Each tree has a unique drip.",
            "The smell of wet November: decay, earth, the end of the growing season.",
            "After November rain, check for late fungi. Some species fruit now.",
            "Wet conditions suit earthworms. Blackbirds work the soggy lawns.",
            "November wet chills in a way October didn't. The cold is deeper.",
            "Rain accelerates decomposition. The leaf layer compresses.",
            "Wet evenings are dark evenings. November after 4 PM is night.",
            "November rain feeds the springs and rivers. Water levels rise.",
        ],
        "snow": [
            "November snow is winter arriving early. It often doesn't stick yet.",
            "First snow of the season often comes in November. The signal is clear.",
            "Snow this month is a preview. More is coming.",
            "November snow on bare trees is the classic early winter image.",
            "If it snows, the landscape transforms suddenly. No transitional color anymore.",
        ],
        "general": [
            "November is the month of bare trees and short days. The transition is complete.",
            "Days are short and getting shorter. The solstice is next month.",
            "Starling murmurations are at their peak. Thousands of birds swirl at dusk.",
            "Migrant birds have arrived: redwings, fieldfares, wintering geese.",
            "Hedgehogs should be hibernating now. Late activity is a concern.",
            "The smell of bonfires and wood smoke is everywhere.",
            "Fungi continue but wind down. The main season is ending.",
            "November asks for adjustment. Indoor lighting, earlier evenings.",
            "The approach to winter solstice accelerates. The darkest days are coming.",
            "Bird feeders become essential. Natural food is scarce.",
        ],
    },
    12: {
        "clear": [
            "December sun is scarce but valuable. Every minute of direct light counts.",
            "Clear winter days around the solstice are cold but beautiful.",
            "The solstice approaches—the shortest day, the turning point.",
            "Cold, clear December means frost-covered landscapes. Worth seeing.",
            "December sun stays low all day. A constant golden-hour quality.",
            "Clear nights are freezing nights. The stars are vivid.",
            "Winter sun on frost creates glittering surfaces.",
            "Clear December days are the best of the short options.",
            "The solstice is the bottom. From here, the days lengthen again.",
            "Robin song returns. They sing through winter to hold territory.",
        ],
        "grey": [
            "Grey December is traditional. The season of artificial light.",
            "Overcast days near the solstice are dark days. The light is minimal.",
            "Grey skies, shortest days—the bottom of the annual cycle.",
            "Holiday lights compensate for what nature doesn't provide.",
            "Grey December is the reason for festive traditions—light against darkness.",
            "The grey is real, but so is the turnaround coming.",
            "Overcast solstice days are the darkest. But they're also the turning point.",
            "Grey doesn't stop the robins singing. They're the winter soundtrack.",
            "The evergreens matter now—holly, ivy, yew, pine. They carry the green.",
            "Grey December makes you appreciate every bright moment.",
        ],
        "rain": [
            "December rain instead of snow—the mild winter version.",
            "Wet winter is its own thing. Less picturesque, more practical.",
            "Rain near the solstice adds to the darkness. Wet and dark together.",
            "The smell of December rain is cold and earthy. Different from summer.",
            "Wet December feeds the soil for spring. The cycle continues.",
            "After December rain, check for fungi. Some bracket fungi fruit all winter.",
            "Wet and dark combined. But the solstice turns the tide regardless.",
            "December rain keeps ground frost away. Milder than clear and frozen.",
            "Wet decaying leaves carpet the ground. The year's leaf fall is complete.",
            "Rain on bare branches—the winter sound.",
        ],
        "snow": [
            "December snow transforms everything. The classic winter image.",
            "Snow amplifies what light there is. The landscape glows.",
            "Holiday snow, if it comes—magical for some, difficult for others.",
            "Snow near the solstice compensates for the short days. The brightness helps.",
            "December snow creates its own light. The world reflects.",
            "Fresh snow reveals animal tracks—the night's activity visible.",
            "Snow on evergreens—holly, pine, yew—creates the archetypal winter scene.",
            "December snow is the most anticipated. It matches the season.",
            "Snow cover changes the light quality. Nights are lighter.",
            "Snow at the solstice is winter in full form.",
        ],
        "general": [
            "December contains the winter solstice—the shortest day, the turning point.",
            "The solstice is not the coldest day, but it is the darkest. The lag is normal.",
            "After the solstice, days lengthen. The psychological boost is real.",
            "Winter birds—robins, wrens, tits—are the main wildlife activity.",
            "Holly berries are ripe. Look for them against evergreen leaves.",
            "The smell of wood smoke and pine marks the season.",
            "Bird feeders are critical now. Natural food is scarce.",
            "December is the bottom of the light cycle. The only way is up.",
            "Evergreens carry symbolic weight—life persisting through darkness.",
            "The solstice marks the return of light. It deserves acknowledgment.",
        ],
    },
}


# ===== ADDITIONAL NATURE FACTS FOR VARIETY =====
# Generic observations to add variety when specifics don't apply
NATURE_FACTS_GENERAL = [
    "Bird feeders see more activity on cold days. The energy demand increases.",
    "Squirrels don't hibernate—watch for them year-round, even in cold weather.",
    "Robins sing year-round in the UK. One of the few birds that holds winter territory.",
    "Foxes are more visible in winter. Less cover, more need to hunt in daylight.",
    "The smell of the season is as diagnostic as the temperature. Each month has its scent.",
    "Cloud patterns tell weather stories. High cirrus often means change coming.",
    "Contrails from aircraft last longer in humid air. A simple weather indicator.",
    "Morning mist burns off when temperatures rise. Watch the process happen.",
    "Puddles freeze from the edges inward. Watch the ice form on cold mornings.",
    "Birds fluff their feathers in cold weather to trap insulating air.",
    "Breath visible in cold air indicates temperature below about 7°C.",
    "Frost forms on clear nights when heat radiates away. Clouds act as a blanket.",
    "Wind makes cold feel colder but doesn't change the actual temperature.",
    "Wet leaves are slippery because of the layer of decomposing matter on their surface.",
    "Trees lose leaves to reduce water loss when the ground is frozen.",
    "Evergreen trees have waxy needles that resist water loss and can photosynthesize all year.",
    "The sun is actually closest to Earth in January. Distance doesn't determine our seasons.",
    "Seasons are caused by Earth's tilt, not its distance from the sun.",
    "Daylight length affects plant and animal behavior more than temperature.",
    "Many birds navigate using Earth's magnetic field. They have built-in compasses.",
]


# ===== TRANSITION CONNECTORS =====
CONNECTORS = {
    "meanwhile": [
        "Meanwhile,",
        "At the same time,",
        "In parallel,",
        "While that's happening,",
    ],
    "contrast": [
        "But here's the thing:",
        "That said,",
        "On the other hand,",
        "However,",
        "Still,",
    ],
    "addition": [
        "What's more,",
        "Beyond that,",
        "Plus,",
        "Adding to that,",
        "Also worth noting:",
    ],
    "consequence": [
        "Which means",
        "So",
        "The result:",
        "That translates to",
    ],
}


# ===== CLOSINGS =====
CLOSINGS = {
    "practical": [
        "Plan accordingly.",
        "Adjust as needed.",
        "Good to know for planning.",
        "Worth factoring in.",
    ],
    "observational": [
        "Worth paying attention to.",
        "Something to notice.",
        "Keep an eye on it.",
        "The details matter.",
    ],
    "simple": [
        "That's the picture.",
        "Those are the facts.",
        "That's where we are.",
        "There it is.",
    ],
}
